### ISSUE TITLE
Gmail SMTP Settings Failure.

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#10]
When using the provided settings, the login fails with my normal account password. But does work when i use a app password. We need to Inform the user that they need too Setup a application password ( 2-Step Verification ) for email alerts to work.

https://support.google.com/mail/?p=InvalidSecondFactor

![screen shot 2017-01-03 at 1 27 54 am](https://cloud.githubusercontent.com/assets/14851974/21601094/e13550cc-d153-11e6-91fb-bc1c3b42ec17.png)

``

UI: 0.7.6

**Comment by jflidr** [comment]
Yes, we will add help/description:

_If your Gmail account uses 2-Step-Verification, you must [generate an App password] and use it in the password field. Otherwise you must ensure that you [allow less secure apps to access your Gmail account]._

with links to google help. It will be available in version 0.7.8

**Comment by Dstahl0** [comment]
Perfect, Thanks @jflidr

**Comment by jflidr** [comment]
Fixed in version 0.7.9

**Comment by cult-hero13** [comment]
I'm running version 0.14.3.  Using the "Gmail" selection from the drop-down menu, and my Gmail credentials, using an app password, I get "There was a SMTP error." when I click the "Send" button.

**Comment by radekskrivan** [comment]
Hello @cult-hero13. First please check all the values. If you are positive that you have everything correct try to upgrade to 1.1.3, there were a few fixes for SMTP.

**Comment by Bigred3030** [comment]
radekskrivan I have the exact same problem. I am running version 1.1.4  I am always getting the stmp error message. I have tried with and without the app created password. I don't know what else to do.

**Comment by radekskrivan** [comment]
Hello @Bigred3030. Make sure you have the correct configuration and you are using the right credentials. If you are using the Gmail setup, make sure you have all the necessary settings for 2FA and using the lesser secured applications.

**Comment by cult-hero13** [comment]
I ran the update(s) yesterday, UNMS 1.1.4, and was able to send emails with the configurations I had tried before.  I'm running the update to 1.1.5 now.  I'll update this thread if it ends up breaking what is working now.


________________________________
