### ISSUE TITLE
Site dropdown not alphabetically sorted

### ISSUE THREAD

**Issue by Wiuff** [Ubiquiti-App/UNMS#101]
![device authorize](https://user-images.githubusercontent.com/34070412/33682065-9faa7e8e-dac6-11e7-8434-7d59da34ad5c.JPG)
upon authorize of a device, I will choose an existing site, these sites will not be presented alphabetically

/Wiuff

**Comment by radekskrivan** [comment]
Thank you @Wiuff  for this report. I created a task for our developers to fix this. I hope it will be done in 0.11.1

**Comment by jflidr** [comment]
Fixed in 0.11.1.
