### ISSUE TITLE
Unknown mac address before authorize

### ISSUE THREAD

**Issue by Wiuff** [Ubiquiti-App/UNMS#102]
![no mac adresse](https://user-images.githubusercontent.com/34070412/33683288-ad344dd8-daca-11e7-8730-1fbfcb9c0755.JPG)

All of my devices are located remotely and connect via WAN. Devices are located on 60 different sites, and here it would be a great advantage if MAC address can be seen before approval, so device can be identified.

/Wiuff

**Comment by radekskrivan** [comment]
Thank you @Wiuff  for clear feedback. I would like to encourage you to share it in our [feature request](https://community.ubnt.com/t5/UNMS-Feature-Requests/idb-p/UNMSFeatureRequests) thread in UNMS community. You will increase the chance of this idea being implemented if it gathers more supporters.

**Comment by Wiuff** [comment]
Feature request created.

/Wiuff
