### ISSUE TITLE
Install on CoreOS

### ISSUE THREAD

**Issue by woopstar** [Ubiquiti-App/UNMS#103]
Hi,

We got the UNMS installed successfully on CoreOS with the following script / hack:

```
# CoreOS UNMS Install
mkdir -p /opt/bin
curl -L `curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r '.assets[].browser_download_url | select(contains("Linux") and contains("x86_64"))'` > /opt/bin/docker-compose
chmod +x /opt/bin/docker-compose
export PATH="/opt/bin/:$PATH"
mkdir -p /tmp/unms
cd /tmp/unms
wget https://github.com/Ubiquiti-App/UNMS/raw/master/unms-0.11.0.tar.gz
tar zxvf unms-0.11.0.tar.gz

# fix install file
sed -i 's/^check_system$/#check_system/' install-full.sh
sed -i 's/^install_docker$/#install_docker/' install-full.sh
sed -i 's/^install_docker_compose$/#install_docker_compose/' install-full.sh
sed -i 's/^build_docker_images$/#build_docker_images/' install-full.sh
sed -i 's/^setup_auto_update$/#setup_auto_update/' install-full.sh
sed -i 's/^confirm_success$/#confirm_success/' install-full.sh

bash install-full.sh
```

How do you feel about a pull request to remove nc to check if UNMS is up in the `confirm_success` function, and instead use `curl` or `wget` - or even let it try all three to make it more generic?

I could also do a pull request to fix the other functions so they are more generic and work on CoreOS too.

**Comment by jflidr** [comment]
@woopstar Hi Andreas, thank you, it sounds very interesting. I have done a few steps which were necessary before it's possible to do any pull requests:
- I have add a folder _[/src](https://github.com/Ubiquiti-App/UNMS/tree/master/src)_ which includes all parts of installation scripts which are bundled in files such as _[unms-0.11.0.tar.gz](https://github.com/Ubiquiti-App/UNMS/blob/master/unms-0.11.0.tar.gz)_. It includes only installation scripts and containers configuration not UNMS as itself. 
- There is a [license](https://github.com/Ubiquiti-App/UNMS/blob/master/LICENSE.md) file for these installation scripts. 

So feel free to do any pull requests.

**Comment by woopstar** [comment]
Pull request added . Please review.

**Comment by jaroklima** [comment]
Closing this PR in favor of #106

**Comment by woopstar** [comment]
@jflidr  Should we close #83 and #85 too ?

**Comment by jflidr** [comment]
@woopstar good point I will close them.
