### ISSUE TITLE
Gallery crashing server

### ISSUE THREAD

**Issue by Simonk007** [Ubiquiti-App/UNMS#109]
When adding multiple pictures to gallery on a site. Server restart.
Isnt is possible to have multiple images on a site or client

**Comment by radekskrivan** [comment]
@Simonk007  It should be possible to have several pictures added to a site. Can you please send me your [UNMS logs](https://github.com/Ubiquiti-App/UNMS/wiki/Discovery-Troubleshooting#where-to-find-unms-logs) to my address radek.skrivan(at)ubnt.com? We suppose there may be some issue with those pictures. Wrong size, format or something like that.

**Comment by Simonk007** [comment]
Hi Radek,
i have sendt you log files using wetransfer

**Comment by Simonk007** [comment]
@radekskrivan which file type, size and format are allowed for pictures in the gallery

**Comment by radekskrivan** [comment]
@Simonk007   All the pictures in one upload had to be smaller than 20MB and the resolution should be lower than 10Mpix.
I would like to confirm that I got your log files and we will have a look at them.
