### ISSUE TITLE
[ Feature Request ] OLT Power Module Status.

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#11]
It would be great to be able to view the Power Module's status of the OLT via unms.

Because at first glance, a FISP( Fiber Internet Service Provider ) will need to see all endpoints of possible issues that could cause a outage / lost of income  and possible customers dropping service. Should one not know a PSU Slot is out and then the other one fails for some reason, it could of been prevented by having a visual status of the PSU Slot's.
 

Possible add PSU1 / PSU2 Status 
With the word Online ( In Green ) or Offline ( In red )
 
Have the Status of the PSU's on this screen as one does not need to click each device to see the status of it.

![screen shot 2017-01-03 at 3 50 40 pm](https://cloud.githubusercontent.com/assets/14851974/21622614/6d5efb34-d1cc-11e6-9ca7-9ab76be74241.png)

If not in that screen, lets see about getting a PSU Tab added after Disconnected? 
All | Active | Disconnected | PSU Status.

Within that have Status | PSU Status | Name | Physical Address | IP Address  

When a PSU is being detected as connected to the olt and not getting 120V power, have a icon on main device panel to turn to Orange With text Degraded.

I can see this as a main feature that can be promoted as you can fully visualise the OLT within unms without having to login to a OLT. I was also thinking of having some sort of button that says Acknowledge PSU outage on a OLT via unms screen with a note like 

Date: Auto filled
Tech: Use Login name.
Notes:  
Submit button

**Comment by amishgenius** [comment]
That would be extremely useful. That is something that could easily be overlooked.

**Comment by jflidr** [comment]
Yes it is a good idea. @MartinStrbacka will let you know when OLT will support&report this new "status". It will be simple to add this feature to UNMS then.

**Comment by MartinStrbacka** [comment]
Agree that this is a good idea. 
There is a hardware support for reading the PSU status so there is a way how to implement it but I can't guarantee that this will be part of the V1.0 release.

**Comment by Dstahl0** [comment]
Thanks for the update @MartinStrbacka  and @jflidr

**Comment by JimBouse** [comment]
I second (or third) this request.  Power status and alerting is very important.  Many of these OLTs will be out in a cabinet somewhere.  We need to be able to schedule a replacement of failed devices.

On another note, I would like to see the power supplies in the front in future revisions.  I know it isn't pretty but it is functional when crammed into a cabinet with fiber and other cables.

**Comment by Dstahl0** [comment]
@jflidr @MartinStrbacka  forward thinking, if WISP UCRM billing will be integrated into this with a ticket system have the values stated above be integrated into the ticket system. if it will add more time to get this function out, i would say make it store the notes in the mongo-db then once the ticket system is completed, copy the values over to the ticket system using a migration script.

Thanks,
DStahl

**Comment by 1WisTech1** [comment]
I'm right there with David, and the others.  This is an important bit of information that should be in big bold letters up top.

**Comment by Alan87i** [comment]
Yeah I like the power status idea.  Would make things a lot easier.

**Comment by radekskrivan** [comment]
Transfered to https://community.ubnt.com/t5/UNMS-Feature-Requests/OLT-Power-Module-Status/idi-p/2164596
