### ISSUE TITLE
Reverse Proxy option missing?

### ISSUE THREAD

**Issue by peripatetic-sojourner** [Ubiquiti-App/UNMS#112]
The wiki says we should use "--behind-reverse-proxy", however, there is no case for this option in the install script. Looking through the tarballs, it appears to have been removed between 10.4 and 11.0.

Is there something missing from the script or does the wiki need to be updated?

**Comment by Taubin** [comment]
There are examples provided in teh wiki

https://github.com/Ubiquiti-App/UNMS/wiki/Reverse-proxy-examples

**Comment by prvak** [comment]
@peripatetic-sojourner This option was removed in 0.11.0. The wiki needs to be updated.
