### ISSUE TITLE
Update roadmap

### ISSUE THREAD

**Issue by woopstar** [Ubiquiti-App/UNMS#113]
It seems the roadmap at https://unms.com/ should be updated.

We are heavily awaiting the Firewall , QoS options :)

**Comment by jflidr** [comment]
@woopstar Hi Andreas, roadmap on https://unms.com/ is correct. We are working on Firewall and QoS right now. UNMS backend should be ready in UNMS 0.12.0. New screens for Firewall and QoS will be available in UNMS 0.13.0 which should be released tightly before the end of Q1 2018. It will be necessary to have EdgeRouter FW 1.10.0+.
