### ISSUE TITLE
update multiple devices at the same time

### ISSUE THREAD

**Issue by slang123** [Ubiquiti-App/UNMS#115]
We have about 200 devices split into 13 sites. When i upgrade the device firmware on each site it only updates one device at a time and ques the next site. It takes about 4-5 minutes for each device, thats 15 hours, if I update all :)

It would be nice if UNMS could optimize this a bit. For example if it started with stations on each Access Point, because they should be able to all update at the same time and then iterate the AP's. Or something like that.

**Comment by radekskrivan** [comment]
@slang123  Hello Tummas. We are working on a solution to this issue. The first version of a parallel FW upgrade will be available with the release of 0.12.0 version. [Here](https://community.ubnt.com/t5/UNMS-Beta/0-11-1-firmware-upgrade-batch-quot-hangs-quot-upgrading-airMAX/m-p/2200154/highlight/true#M3516) is a post on our community with some more info.

**Comment by slang123** [comment]
@radekskrivan that sounds good, looking forward to it :)
