### ISSUE TITLE
UNMS 0.11.2 UPDATE makes devices gone

### ISSUE THREAD

**Issue by jasonobrien99** [Ubiquiti-App/UNMS#116]
Hello, after updating from 0.11.1 to 0.11.2 through the GUI in UNMS, non of the devices are being seen by UNMS.  All are saying disconnected.  All devices are running 6.1.4cs.  I can’t see the issue.  Any help appreciated.

**Comment by radekskrivan** [comment]
@jasonobrien99   Thank you for the report Jason. Here is a [link](https://community.ubnt.com/t5/UNMS-Beta/NanoStation-LocoM5-dont-connect-UNMS-0-11-0/m-p/2223680#M4024) to our community where we are solving this.

**Comment by radekskrivan** [comment]
@jasonobrien99  please try the new 0.11.3 the issue should be resolved there.
