### ISSUE TITLE
UNMS 0.11.3, discovery does not work.

### ISSUE THREAD

**Issue by zar1n** [Ubiquiti-App/UNMS#117]
Hello,
After update to 0.11.3, discovery does not work. Circle progress bar spinning and nothing happening.
Thank you.

**Comment by jflidr** [comment]
@zar1n Hi, could you please send ranges which you are trying to discover and [UNMS logs](https://help.ubnt.com/hc/en-us/articles/115015690107) to @radekskrivan (radek.skrivan(at)ubnt.com)

**Comment by radekskrivan** [comment]
I received both ranges and logs. I will create a task for our developers to analyze what may be going on.

**Comment by radekskrivan** [comment]
Hello. I am closing this thread since it is no longer active. In case you still need our help, please leave a comment.
