### ISSUE TITLE
[ Feature Request ] Firmware Manager For OLT's Via UNMS

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#12]
So after adopting the olt's, i see the that since everything is being "managed" via the unms, there is really no need now too log into the OLT for much of anything else but pon port settings but i will cover that in another issue track.

it would be nice to see something like this in the settings window of unms where we can upload the firmware to the data dir that is located outside of the docker container for unms which manages the olt and the upcoming other products which will remain nameless for now and update the different OLT's

![screen shot 2017-01-04 at 11 11 41 pm](https://cloud.githubusercontent.com/assets/14851974/21668792/30d22346-d2d3-11e6-964d-442ffee7ce2f.png)

Clicking on lunch, will bring a window up listing the devices  of the known OLTS's And show the user something like this

************************************************************
* Name                  |      Status   | Version         |   Upgrade
* LSP-Hood-#231     Online          0.2.5                 0.2.6
* LSP-Hood-#222    Online          0.2.3                 0.2.6
X Select All >- Upgrade Devices  
************************************************************

What do you guys think?
@JimBouse
@amishgenius
@1WisTech1 
@MartinStrbacka

**Comment by 1WisTech1** [comment]
I completely agree with you.  I think that type of option to upload firmware to the data directory would be very, very useful.  Nice suggestion buddy.

**Comment by Dstahl0** [comment]
Thanks @jflidr for the update.

**Comment by JimBouse** [comment]
Will we also have an option to push firmware to the ONUs?

**Comment by Dstahl0** [comment]
+1 @JimBouse i would expect this to be located under the ouns tab..  @jflidr ?

**Comment by jflidr** [comment]
@JimBouse @Dstahl0 Yes, there will be FW upgrade available for all UNMS devices (OLTs, ONUs, EdgeRouters...). All items in all devices lists will have upgrade button + there will be mass FW upgrade in "Firmware manager".

**Comment by jflidr** [comment]
There is a Firmware Manager in 0.7.14.which supports ONU upgrades. Upgrade of other devices will be available in the next version 0.7.15.

**Comment by jflidr** [comment]
Firmware Manager can upgrade all devices in the last version 0.7.15.
