### ISSUE TITLE
Does not work with ARM / RaspberryPi

### ISSUE THREAD

**Issue by heldstma** [Ubiquiti-App/UNMS#120]
I would love to see support for ARM / Raspian.  My UniFi deployment is on a RaspberryPi and I would love to run UNMS on the same platform.

**Comment by MajoV** [comment]
@heldstma 
I would like to recommend these threads, here you will find more information about running UNMS on the ARM platform.
https://community.ubnt.com/t5/UNMS-Beta/UNMS-on-Docker-for-Mac/m-p/2140572#M2345
https://community.ubnt.com/t5/UNMS-Beta/UNMS-in-Raspberry-Pi-3/m-p/2155881#M2551
https://github.com/oznu/docker-unms

Majo

**Comment by heldstma** [comment]
Fantastic!  Thank you.
Matt
