### ISSUE TITLE
tr: Illegal byte sequence on macOS

### ISSUE THREAD

**Issue by JannikArndt** [Ubiquiti-App/UNMS#122]
I received the following error when running the installer on macOS 10.13.3:

```bash
$ ./install.sh 
branch=master
version=0.11.3
Downloading installation package for version 0.11.3.
tr: Illegal byte sequence
```

Diving into the issue, `head -c 500 /dev/urandom | tr -dc A-Za-z0-9` (from https://github.com/Ubiquiti-App/UNMS/blob/master/src/install-full.sh#L28) fails if `LC_ALL` is not set. 

Running `export LC_ALL=C` fixes the issue. Maybe you could build in a check so the next guys doesn't have to dive into the source code ;)

**Comment by jflidr** [comment]
@JannikArndt thank you for your fix. It will be included in UNMS 0.12.0.
