### ISSUE TITLE
unms_install script conflicting with get-docker.sh

### ISSUE THREAD

**Issue by Kentix** [Ubiquiti-App/UNMS#124]
When attempting to install UNMS on a fresh Ubuntu 16.04 LTS, the error below is thrown about midway.

_"ERROR: '0.11.3' not found amongst apt-cache madison results"_

Speculatively, I believe this is a conflict with the variable $version used in both the unms_install.sh script and get-docker.sh which is ultimately called when a dependency is found to be absent.

I tested this on Ubuntu 16.04 LTS only but suspect it would happen if the docker dependency is not present. 

The following worked for me:

Run the following, first, and then re-run unms_install.sh from /tmp.

**curl -fsSL get.docker.com -o get-docker.sh
sh get-docker.sh**

A UBNT community post details this slightly more, the link is below. I attached the get-docker.sh [txt] and my slightly modified unms_install.sh [txt], though the latter may be unnecessary.

https://community.ubnt.com/t5/UNMS-Beta/Issue-installing-UNMS-ERROR-0-11-3-not-found-amongst-apt-cache/m-p/2257050/highlight/false#M4701

[unms_install.txt](https://github.com/Ubiquiti-App/UNMS/files/1755387/unms_install.txt)
[get-docker.txt](https://github.com/Ubiquiti-App/UNMS/files/1755390/get-docker.txt)

**Comment by jflidr** [comment]
@Kentix Thank you for reporting it and your solution. We will check it and bundle fix to the installation script ASAP. I think that it will be in 0.12.0-beta.2

**Comment by jflidr** [comment]
Installation of the latest version 0.11.3 is fixed.
