### ISSUE TITLE
ERROR: '0.11.3' not found amongst apt-cache madison results

### ISSUE THREAD

**Issue by apetzel** [Ubiquiti-App/UNMS#125]
when deploying on ubuntu 16.04 on GCP following error occures:

INFO: Searching repository for VERSION '0.11.3'
INFO: apt-cache madison 'docker-ce' | grep '0.11.3.*-0~ubuntu' | head -1 | cut -d' ' -f 4

ERROR: '0.11.3' not found amongst apt-cache madison results

when manually launching apt-cache madison 'docker-ce'
versions from docker get shown and not UNMS version 0.11.3. 
as listed below:
 docker-ce | 18.02.0~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/edge amd64 Packages
 docker-ce | 18.01.0~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/edge amd64 Packages
 docker-ce | 17.12.0~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/edge amd64 Packages
 docker-ce | 17.11.0~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/edge amd64 Packages
 docker-ce | 17.10.0~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/edge amd64 Packages
 docker-ce | 17.09.1~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/edge amd64 Packages
 docker-ce | 17.09.0~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/edge amd64 Packages
 docker-ce | 17.07.0~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/edge amd64 Packages
 docker-ce | 17.06.2~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/edge amd64 Packages
 docker-ce | 17.06.1~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/edge amd64 Packages
 docker-ce | 17.06.0~ce-0~ubuntu | https://download.docker.com/linux/ubuntu xenial/edge amd64 Packages
 docker-ce | 17.05.0~ce-0~ubuntu-xenial | https://download.docker.com/linux/ubuntu xenial/edge amd64 Packages
 docker-ce | 17.04.0~ce-0~ubuntu-xenial | https://download.docker.com/linux/ubuntu xenial/edge amd64 Packages

**Comment by jflidr** [comment]
@apetzel Hi Andreas, thank you for reporting it. It should be fixed right now. Could you please try it again? Thank you.

**Comment by apetzel** [comment]
works like a charm
