### ISSUE TITLE
Allow disconnected antenna for a period of time

### ISSUE THREAD

**Issue by slang123** [Ubiquiti-App/UNMS#129]
On most of our sites we have a few bullets on small vessels. And from time to time they disconnect from the APs for a few hours, and then the site goes red.
Will it be possible in the future to acknowledge a disconnection for a set time, so the site goes back to the color green? Or is there perhaps some other way I can do this?

The reason is of course we don't want to have red sites on our monitors

**Comment by radekskrivan** [comment]
@slang123  Hi Tummas. Your suggestion is very similar to [this](https://community.ubnt.com/t5/UNMS-Feature-Requests/Feature-request-Maintenance-mode-for-devices-disable-outage/idi-p/2268062) feature request. May I suggest to leave a comment there, and I will close this ticket on GitHub?

**Comment by slang123** [comment]
perfect, you can close this
