### ISSUE TITLE
[ Possible Bug ] appActionBar appActionBar--cozy  ( Not Responsive? )

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#13]
Logging into 0.7.9, Clicking Device name under /sites results in the following display when not full width.

with normal view not zoomed.
![screen shot 2017-01-06 at 3 21 58 pm](https://cloud.githubusercontent.com/assets/14851974/21731744/e81cd4c8-d423-11e6-90fc-13d34fc058bc.png)

![screen shot 2017-01-06 at 3 21 36 pm](https://cloud.githubusercontent.com/assets/14851974/21731737/d8d8936c-d423-11e6-9a01-f5acd46136b8.png)

Now with max screen width wide. 

![screen shot 2017-01-06 at 3 22 51 pm](https://cloud.githubusercontent.com/assets/14851974/21731765/06165ddc-d424-11e6-9405-d5bbe8bd049a.png)

Is there anyway we can get it to be a responsive action as like the other content directly below it? or if not bump it to dual lines so it still shows the content.?

Thanks,
DStahl

**Comment by jflidr** [comment]
It is not response for now but we will fix it in version 0.7.11.

**Comment by Dstahl0** [comment]
Thank you very much. 

DStahl.

**Comment by jflidr** [comment]
Fixed in version 0.7.10

**Comment by Dstahl0** [comment]
Thank you 👍
