### ISSUE TITLE
Allow Public Key Certificates to be used for Discovery/credentials

### ISSUE THREAD

**Issue by kwesibrunee** [Ubiquiti-App/UNMS#130]
Is it possible to allow certificate authentication for credentials? We are currently exploring a setup where no SSH users are allowed to authenticate to the radio. It would be nice if doing this would not exclude us from using UNMS.

**Comment by radekskrivan** [comment]
@kwesibrunee  That is an interesting idea. I will ask developers to research it.

**Comment by radekskrivan** [comment]
@kwesibrunee  The feature you asked will be added in some of the later versions.
