### ISSUE TITLE
External IP / Internal IP error not yet fixed

### ISSUE THREAD

**Issue by honeyfairy** [Ubiquiti-App/UNMS#133]
_[An old issue posted details the problem. But that is closed, so I'm opening a new one.]_

## Issue
If you have a domain name, connection to devices fail with this error:
Error: Connection attempt has failed * (Waiting for device connect timeout)

Example: unms.isp.com pointing to your external address: 197.50.10.145 and your server is hosted with a local IP of 172.16.0.100.
Then you get this error. But once you change the UNMS settings Host url from  unms.isp.com to  172.16.0.100 then it works

**Comment by radekskrivan** [comment]
@honeyfairy  Hello Alisha. There was a major DNS bug in last bet.1 FW. Please make sure you have either stable 8.5.1 / 6.1.6 or you are running beta.2.

**Comment by florisvdk** [comment]
This sounds more like a hairpin nat issue.

**Comment by dingerkingh** [comment]
I have this same problem. I use hairpin NAT but it does not work with UNMS authentication. I always have to hardcode the private ip of the server. Hairpin is set up correctly as I can browse to UNMS in my browser using the DNS name but UNMS devices can't connect using DNS name.

**Comment by radekskrivan** [comment]
@dingerkingh Hello. We are preparing an article about setting up the NAT rules to avoid this situation. The article will contain a guide how to use one UNMS key for all devices (inside and outside the network) and configure NAT so that it works. Please keep an eye on our [help site](https://help.ubnt.com/hc/en-us/sections/115003321288-UNMS-Ubiquiti-Network-Management-System).

**Comment by dingerkingh** [comment]
Awesome - thanks! I am quite excited about that.

**Comment by honeyfairy** [comment]
Thank you for the replies. 
I really need that help file, please let us know when its available. 
NAT rules in Mikrotik and/or Edge routers right?

**Comment by dingerkingh** [comment]
https://help.ubnt.com/hc/en-us/articles/360003333934-UNMS-Connecting-Devices-in-Private-IP-Range
