### ISSUE TITLE
Install Script Failing

### ISSUE THREAD

**Issue by mstarr68** [Ubiquiti-App/UNMS#136]
Command line run, as well as results and error message below.

$ curl -fsSL https://raw.githubusercontent.com/Ubiquiti-App/UNMS/master/install.sh > /tmp/unms_install.sh && sudo bash /tmp/unms_install.sh
branch=master
version=0.12.0
Downloading installation package for version 0.12.0.
Setting VERSION=0.12.0
Download and install Docker
# Executing docker install script, commit: 92d5116
+ sh -c apt-get update -qq >/dev/null
W: The repository 'cdrom://Ubuntu-Server 16.04.1 LTS _Xenial Xerus_ - Release amd64 (20160719) xenial Release' does not have a Release file.
E: Failed to fetch cdrom://Ubuntu-Server 16.04.1 LTS _Xenial Xerus_ - Release amd64 (20160719)/dists/xenial/main/binary-amd64/Packages  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by prvak** [comment]
You have `cdrom` repository configured as a source in `/etc/apt/sources.list`. You should remove or comment out lines containing `cdrom` from `/etc/apt/sources.list`. [This answer](https://askubuntu.com/a/42445) explains how to do that.
