### ISSUE TITLE
indicate port for devices

### ISSUE THREAD

**Issue by franrtorres77** [Ubiquiti-App/UNMS#138]
Hi, 

Is it possible to change the default port 80 and 443 for specific ones. I mean, we want to open directly our devices from UNMS but we always have to add oru specific port, such as this example: 192.168.1.20:38443

Regards

**Comment by radekskrivan** [comment]
@franrtorres77   Hello Fran. You can set up a custom port during [installation](https://help.ubnt.com/hc/en-us/articles/360000119728-UNMS-Optional-Installation-Steps#5).

**Comment by franrtorres77** [comment]
Is it possible to change it after the installation ?

**Comment by radekskrivan** [comment]
@franrtorres77  Yes, the best way is to call the installation script again with the --update parameter and either --http-port <NUMBER> or --https-port <NUMBER> parameter according to what you need to change.

**Comment by franrtorres77** [comment]
Hi @radekskrivan but I meant the stations port, not the unms port for listening the devices. What I want is to be able to open directly the station on the browser with the port specified. i.e. https://192.168.1.20:**38443**

**Comment by franrtorres77** [comment]
Thank you @radekskrivan
