### ISSUE TITLE
Upgrade stations

### ISSUE THREAD

**Issue by franrtorres77** [Ubiquiti-App/UNMS#139]
Hi, it would be nice and very usefull to upgrade the stations related to an AP from Unms, would it be possible? 

Regards

**Comment by radekskrivan** [comment]
@franrtorres77  Hello Fran. I am not entirely sure what your question is about. If you have those stations added to UNMS then you can upgrade their FW for sure.

**Comment by franrtorres77** [comment]
Well, we don't use to add the stations to UNMS, so I meant in the moment when you click in the station section of each device.

**Comment by radekskrivan** [comment]
@franrtorres77   I am sorry Fran, this is not something UNMS can do. We only support an upgrade during UNMS discovery because at that moment UNMS can see the device and also you can upgrade a device that is connected to UNMS because the connection is established at that time.

**Comment by radekskrivan** [comment]
Hello. I am closing this thread since it is no longer active. In case you still need our help, please leave a comment.
