### ISSUE TITLE
[ Feature Request ] OLT Temperature Values.

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#14]
Having Temperature values being displayed is also very important to a WISP / FISP that has road side cabinets in use. This can possibly save the wisp / fisp hundreds if not thousands of dollars should a cabinet fan or fans fail / ring has issues and this starts the flood of support calls..

Any chance we can also get these values added to unms? and if so i would say display it along side with #11

**Comment by MartinStrbacka** [comment]
Thanks @Dstahl0. Point taken, ticket created.

**Comment by 1WisTech1** [comment]
+1 on this.

**Comment by radekskrivan** [comment]
Accepted in https://community.ubnt.com/t5/UNMS-Feature-Requests/New-Statistic-Temperuture/idi-p/1836204
