### ISSUE TITLE
Update from 0.12.0 doesnt work? 

### ISSUE THREAD

**Issue by stefanlivens** [Ubiquiti-App/UNMS#140]
I have a Virtualbox with Ubuntu server and UNMS 0.12.0 on my Mac.
Upon clicking the "check for updates" in the Maintenance-pane of UNMS, I get the response "UNMS is up to date".

It did seem to know there where new firmware versions (latest is from May 9th) so it seems it has a connection to the internet.

**Comment by radekskrivan** [comment]
@stefanlivens  Hello, the behavior you described is correct. Version 0.12.0 is really the latest **final** release of UNMS. The way it works is that when we are working on a new version we are creating a testing alpha, beta and RC releases only for people visiting Alpha community forum. That way we can be sure that the final version (which can be later downloaded by app-in updater) doesn't contain some serious errors.

**Comment by radekskrivan** [comment]
@stefanlivens  Hello. We just released next version of UNMS 0.12.1. Your in-app upgrade should detect this and allow you to upgrade your UNMS instance.
