### ISSUE TITLE
Unable to Adopt ER4

### ISSUE THREAD

**Issue by f3st3r113** [Ubiquiti-App/UNMS#149]
Looking for assistance, I have UNMS setup on a ubuntu server behind a caddy reverse proxy. 
via (curl -fsSL https://unms.com/install > /tmp/unms_inst.sh && sudo bash /tmp/unms_inst.sh --public-https-port 443 --http-port 8080 --https-port 8443)

When I attempt to adopt my ER 4, it gives me a "Connection attempt has failed" (waiting for device connect timeout)

I've tried using the FQDN as well as the IP and also setup DNS forwarding (set service dns forwarding options address=/unms.example.com/10.10.10.10) on the ER4.

Any assistance is appreciated.

**Comment by radekskrivan** [comment]
@f3st3r113 Hello. In order to help you, we will need some data. First, the device support info, and it would also be good to have the outcome of a ping command from the device to the URL address that is contained in the UNMS key currently inserted in the device. Please do the ping really long, like ten minutes and let us know if there were any disconnects and what was the longest latency.

**Comment by f3st3r113** [comment]
This is local:

![image](https://user-images.githubusercontent.com/21040675/44091498-9ef20ee0-9f9b-11e8-88d7-69a6f1381158.png)

This is to the FQDN
![image](https://user-images.githubusercontent.com/21040675/44091527-c86c3bba-9f9b-11e8-88ca-4b6cefde4e9e.png)

How would I get my device support information to you?

**Comment by f3st3r113** [comment]
OK, I modified the Site/IP to the local IP and ensured that the UNMS key had 8443 and it now adopts.

Why does it not adopt with the FQDN though?

**Comment by radekskrivan** [comment]
@f3st3r113  The first possibility that comes to my mind is that there may be several DNS servers set up and the ping is choosing the primary one (which is all right and the ping goes through) but the connector chooses the secondary one which is either empty or wrong thus failing to connect. Can you please check this? I suppose you already tried to ping the FQDN from the device and it went all right, is that correct?

**Comment by f3st3r113** [comment]
the UNMS server is on my main LAN, which points to my DNS server (PiHole). 

I have PINGed the PiHole DNS and the secondary DNS (1.1.1.1) and both work.

Unless you are asking me to do something else.

**Comment by radekskrivan** [comment]
@f3st3r113  We will need to run through your logs then. I see that you emailed me some of them but I am not able to find anything with your nick in my mailbox. Can you please set up your device with FQDN UNMS key, let it run for a while and send me those logs again? Please make sure you sign as f3st3r113 and include URL of this thread in the message. That should help me to find your message.

**Comment by f3st3r113** [comment]
https://github.com/Ubiquiti-App/UNMS/issues/149#issuecomment-414247196 <https://github.com/Ubiquiti-App/UNMS/issues/149#issuecomment-414247196>

Radek, 

Here are the logs from the ER4.  Let me know if you need anything else.





f3st3r113

**Comment by f3st3r113** [comment]
alright, I emailed you again with the log files.

**Comment by radekskrivan** [comment]
@f3st3r113  I am sorry @f3st3r113, no email from you is in my mailbox. Can you please give me your email address so we can try to connect the other way?

**Comment by f3st3r113** [comment]
You can send to redlineice at g m a i l . c o m

**Comment by radekskrivan** [comment]
Thank you @f3st3r113 . Email sent. Hopefully, we will be able to establish a communication line this way.

**Comment by f3st3r113** [comment]
ok, here is my support file.  I updated as of this morning.

f3st3r113

**Comment by radekskrivan** [comment]
Hello. I am closing this thread since it is no longer active. In case you still need our help, please leave a comment.
