### ISSUE TITLE
[ Feature Request ]  Display Optical Vender Name

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#15]
So within a site and viewing a OLT, it would be nice to have it where we can view what vender module is in use. Because right now there is no way to view what vender module is in what port or if it is even being detected. Just trying to carry some functions over from the EdgeOS Platform.

From

Status | Name | Type | IP | POE | RX RATE | TX RATE | DROPPED | ERRORS | ACTIONS

To

Status | Name | Type | Vender | IP | POE | RX RATE | TX RATE | DROPPED | ERRORS | ACTIONS

Ideas?
@MartinStrbacka 
@JimBouse 
@1WisTech1 
@Alan87i

**Comment by jflidr** [comment]
It's going to be available in the version 0.7.11

**Comment by jflidr** [comment]
It is implemented in the version 0.7.11.

**Comment by Dstahl0** [comment]
Thank you @jflidr and too  everyone over there on the team / Remote Team's as this is appreciated, Keep up the good work everyone! 

Thanks,
David Stahl

**Comment by jflidr** [comment]
@Dstahl0 You're always welcome. Feature requests and bug reports are really important for us because the UNMS is here for you.

**Comment by sinewaveinc** [comment]
How about Optical power levels as well?
