### ISSUE TITLE
Some notes on the 13.0-rc1

### ISSUE THREAD

**Issue by traderose** [Ubiquiti-App/UNMS#150]
I upgraded to 13.0-rc1 yesterday and I found that huge improvements especially airmax configuration and discovery.

However,I have some notes on that after quick review:

1. the discovery now list any device that is either connected to unms or not even 3rd party; which really good improvement. However, when I tried to connect to airmax device,for example, I tried to select the device as usual to be able to provide credentials and connect but wasn't able to do bcz (buttons are disabled)

2. on devices tab, there was refresh button where I was able to get some devices connected back when I click on it, and it seems that button is removed on the new release.

**Comment by traderose** [comment]
![image](https://user-images.githubusercontent.com/30375013/46147739-02dd0e00-c26f-11e8-9bea-23dba944b401.png)

1. Here you can see that I am selecting the not connected ubnt devices, I am unable to provide credentials and connect. 
Also, the selective check box is not available, where you can selectively choose devices for set cred./connect.
The "ADD" button : It looks to me it just useful for third party devices, where you can pull details using snmp. Even if its used for ubnt devices, it uses snmp not unms key.

2. Thanks for clarification. but is there solution to unms key for bunch of devices in one bounce? because if you can see below, I have more 250 devices appear as disconnected while they are online.

![image](https://user-images.githubusercontent.com/30375013/46148260-5439cd00-c270-11e8-83e7-06ec6a202e9e.png)

**Comment by radekskrivan** [comment]
Hello @traderose.
1, Those devices are not recognized as Ubiquiti, therefore UNMS doesn't offer those options. Can you please do the discovery again and send me your UNMS [support info](https://help.ubnt.com/hc/en-us/articles/115015690107-UNMS-How-to-Create-Logs-and-Report-Bugs)?
2, On the screen you provided I can only see one device with AES key issue. This button really is not meant to be used on disconnected devices, it should only work as an emergency for situations when you need to delete a device's AES key from the UNMS internal records.

**Comment by traderose** [comment]
Hi @radekskrivan.
1. the devices those not recognized are  UBNT Airmax AC CPEs. Even those in unknown status are UBNT Airmax CPE devices.
How can I send support file to you? Can you provide with me with an email address to send it to?

Thanks

**Comment by radekskrivan** [comment]
@traderose  No email received yet. Can you please resend the message and make sure it contains your nickname and URL of this thread?

**Comment by traderose** [comment]
I just sent it again now

**Comment by traderose** [comment]
Hi @radekskrivan  can you confirm if you get email? I sent it again 3 days ago

Thanks

**Comment by radekskrivan** [comment]
I have your email @traderose thank you very much for sending it. I am forwarding it to developers now.

**Comment by radekskrivan** [comment]
Hello @traderose. We checked your logs and it is clear that UDP discovery packets do not reach UNMS. There is a number of possible reasons for that. Please check of UBNT discovery is enabled on those devices. If there is an EdgeRouter in your network you can open its UI and click on 'tools' in the upper right corner and select 'discovery'. It will show you UBNT devices nearby that router. You can run tcpdump on the UNMS server to see if those UDP packets are returning. Regarding those devices that appear as Unknown: Do they have the latest FW? Are they in router or bridge mode? Is there some network device between them and UNMS server that can possibly block communication on port 10001 or UDP traffic generally?

**Comment by radekskrivan** [comment]
Hello. I am closing this thread since it is no longer active. In case you still need our help, please leave a comment.
