### ISSUE TITLE
Enable Let's Encrypt not available

### ISSUE THREAD

**Issue by HenryEZ** [Ubiquiti-App/UNMS#151]
When I try to enable Let's Encrypt I get an error stating that I need credentials
tried running this script to resolve cert issue but no luck 

 sudo curl -fsSL https://github.com/Ubiquiti-App/UNMS/blob/master/src/nginx/refresh-certificate.sh > /tmp/refresh-certificate.sh && sudo bash /tmp/refresh-certificate.sh --lets-encrypt "unms.domain.com"
/tmp/refresh-certificate.sh: line 9: syntax error near unexpected token `newline'
/tmp/refresh-certificate.sh: line 9: `<!DOCTYPE html>'

**Comment by radekskrivan** [comment]
@HenryEZ Hello Michal. Please check your SMTP settings, it seems, that you maybe did not enter the SMTP credentials on that page.

**Comment by HenryEZ** [comment]
they SMTP server was set to no auth so not sure why it wanted the credentials. But I disabled the SMTP and then was able to enable Let's Encrypt. 
Thanks,
