### ISSUE TITLE
Feature Request: Firmware Manager Link to Release Notes

### ISSUE THREAD

**Issue by jmhardison** [Ubiquiti-App/UNMS#152]
### Feature Requested

Add link to firmware listing allowing a direct link to the release notes .txt file on ubnt.com.

### Description

As a user, I would like the ability to see a link for `Release Notes` in order to easily access the relevant release notes.

### Notes

I might have missed this in the app, but if not, I'm asking it here. (I have dug around a bit and don't see it in the firmware manager listing.) I'm thinking in the list of available firmware, maybe next to or around the tar file name that is a link to download the tar file, add a `Release Notes` link. This link would take us directly to the ubnt.com hosted page for viewing the release notes. In theory, you could also do a hovering window to display the notes similar to when you pop the window to select devices to upgrade. But I'll settle simply for a direct link to the notes.

**Comment by radekskrivan** [comment]
@jmhardison  Hello Jonathan. Thank you for the feedback. We are already working on this feature, but it is a long time project across all products. I will be definitely done in the future though.

**Comment by jmhardison** [comment]
@radekskrivan Fantastic! I'm fine closing this if you like, or if you want to hold it open to associate to a future PR that's cool to. And I'll just go back to my cave and wait impatiently.

**Comment by NextBlaubeere** [comment]
I think this could be opened again, because it is still not implemented and would be a great improvement for all network-administrators. 👍

**Comment by dutch2005** [comment]
yes please add this, especially now with the "new" forums were seaching is... pita

**Comment by radekskrivan** [comment]
@NextBlaubeere @dutch2005 Hello guys. We agree that this feature is useful and we are still planning to implement it. Unfortunately, I cannot give you any ETA when this will be finished.
