### ISSUE TITLE
POE indicators on SFP X

### ISSUE THREAD

**Issue by smeyernyc** [Ubiquiti-App/UNMS#153]
I find that there are often mismatches between UNMS and device port setting.
![screen shot 2018-10-04 at 12 31 23 pm](https://user-images.githubusercontent.com/29100931/46491896-08d86f00-c7da-11e8-8cdc-7448e85ff680.png)

**Comment by radekskrivan** [comment]
Hello. I am closing this thread since it is no longer active. In case you still need our help, please leave a comment.
