### ISSUE TITLE
API OLTS

### ISSUE THREAD

**Issue by LynSisCZ** [Ubiquiti-App/UNMS#154]
Hello, i have problem with OLTS list (API) 
![image](https://user-images.githubusercontent.com/7085389/46571134-03149200-c970-11e8-94eb-062fa2293aba.png)

**Comment by radekskrivan** [comment]
@LynSisCZ  Hello Lukáš. This API ('GET /devices/olts') was unfortunately removed with 0.13.0. I will make sure we update the documentation accordingly. 
You can use a more general command 'GET /devices' but you will need to filter devices with 'identification.type = olt' afterwards.

**Comment by radekskrivan** [comment]
Hello. I am closing this thread since it is no longer active. In case you still need our help, please leave a comment.
