### ISSUE TITLE
UNMS disconnected emails

### ISSUE THREAD

**Issue by martijnrusschen** [Ubiquiti-App/UNMS#156]
Since the latest update of UNMS, I'm getting multiple emails a day about ubnt being disconnected from UNMS. This has never been a problem, and I'm wondering what's going wrong here.

Here's the email:
> Hi mrusschen,
> 
> you may want to see the following report from 19 Oct 2018 4:17. Latest events are first:
> 
> ubnt connected back to UNMS.
> ubnt has been disconnected from UNMS.
> 
> For login into UNMS proceed to: <redacted>
> 
> UNMS

Versions:
- UNMS: 0.13.0
- EdgeRouter X SFP: 1.10.7

This all started around October 1st.

**Comment by radekskrivan** [comment]
@martijnrusschen Hello. This is fixed in 0.13.1-alpha.1

**Comment by martijnrusschen** [comment]
Thanks, is there an ETA on the fix?

**Comment by radekskrivan** [comment]
@martijnrusschen You can try our latest version [0.13.1-rc.2](https://community.ubnt.com/t5/UNMS-Alpha/UNMS-version-0-13-1-rc-2-has-been-released/m-p/2559944#M2761). Please be aware that you need to be a member of [Early access program](https://help.ubnt.com/hc/en-us/articles/204908664-How-To-Sign-Up-for-Early-Access) for this link to work.

**Comment by martijnrusschen** [comment]
Upgraded to 0.13.1 and it indeed fixed the issue.
