### ISSUE TITLE
0.13.0 cannot connect to SMTP without credentials

### ISSUE THREAD

**Issue by pantsmanuk** [Ubiquiti-App/UNMS#157]
As the subject says, in 0.13.0 you cannot talk to a "no credentials needed" SMTP server.

If you leave the credentials blank and the credentials checkbox unticked, when you save you'll receive a "Credentials required" validation error.

**Comment by radekskrivan** [comment]
@pantsmanuk  Hello Murray, please try the latest 0.13.1-alpha.1. It should be fixed there.
