### ISSUE TITLE
Windows 10 Subsystem for Linux

### ISSUE THREAD

**Issue by Jonatino** [Ubiquiti-App/UNMS#158]
I'm trying to get UNMS running on the windows subsystem for Linux but I'm running into some trouble. I keep getting the following error. 

![alt text](https://dl.dropboxusercontent.com/s/r939ctmr13t4fdx/ubuntu_2018-10-30_10-15-58.png)

I've completed the following guide to get docker working on the WSL (https://medium.com/@sebagomez/installing-the-docker-client-on-ubuntus-windows-subsystem-for-linux-612b392a44c4) but UNMS installation still fails.

Thanks

**Comment by radekskrivan** [comment]
Hello. I am closing this thread since it is no longer active. In case you still need our help, please leave a comment.
