### ISSUE TITLE
Newly released version 0.13.1 not yet listed as 'latest-version'

### ISSUE THREAD

**Issue by slamont** [Ubiquiti-App/UNMS#159]
The installation script is looking for the content of the file 'latest-version', but it seems that it seems that it was not updated when 0.13.1 got released.

We are waiting for it to see if #157 is fixed for us.

**Comment by radekskrivan** [comment]
@slamont  Hello Sylvain, it should be ok now. Please give it a try and let me know if there is still an issue.

**Comment by radekskrivan** [comment]
Hello Sylvain. It seems there was either some network error or a temporary issue with the docker repository.
