### ISSUE TITLE
[Feature Request ] LDAP Login

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#16]
@jflidr While some users that will use this have ldap services running for there company, i do see this as each tech can be assigned a login name for windows and also use it to login UNMS. i think this needs come somewhere within the (Spring 2017) time frame which will give us some testing time to iron bugs out. It would be another features we can show off in the v1 press release.

**Comment by mathse** [comment]
+1

**Comment by radekskrivan** [comment]
Suggested in https://community.ubnt.com/t5/UNMS-Feature-Requests/Multiple-Authentication-Options/idi-p/1815890
