### ISSUE TITLE
Problem with API Site Create

### ISSUE THREAD

**Issue by LynSisCZ** [Ubiquiti-App/UNMS#160]
Hello, i have problem with Create Site (API)
Response from UNMS: `{"statusCode":400,"error":"Bad Request","message":"\"CreateSite\" must be an object","validation":{"source":"payload","keys":[""]}}`

Code: 
[
![image](https://user-images.githubusercontent.com/7085389/49907658-67276b00-fe77-11e8-83c2-0450d19a5970.png)
](url)
[![image](https://img.lynsis.cloud/u/01.36.01-13.12.18.png)](url)

Response and Data (Sent) 
[![image](https://img.lynsis.cloud/u/01.37.40-13.12.18.png)](url)

**Comment by LynSisCZ** [comment]
And second questio: How get Stations (Clients) connected to UBNT from UNMS ? (without add the devices to UNMS)

**Comment by ubnt-michals** [comment]
@LynSisCZ 

My guess use CURLOPT_POST instead of CURLOPT_POSTFIELD

```php
curl_setopt($curl_init, CURLOPT_POST, $dataJson);
```

**Comment by radekskrivan** [comment]
@LynSisCZ  Hi Lukas. For your second question, we are not sure what you mean. Please send me an email with more details to radek.skrivan(at)ubnt.com. You can use Czech if you prefer.

**Comment by LynSisCZ** [comment]
> @LynSisCZ
> 
> My guess use CURLOPT_POST instead of CURLOPT_POSTFIELD
> 
> ```
> curl_setopt($curl_init, CURLOPT_POST, $dataJson);
> ```

Same result. :/ 

`{"statusCode":400,"error":"Bad Request","message":"\"CreateSite\" must be an object","validation":{"source":"payload","keys":[""]}}`

**Comment by LynSisCZ** [comment]
@ubnt-michals https://github.com/LynSisCZ/g2/blob/master/unms.php
