### ISSUE TITLE
No OSPF, DHCP or Tunnel interfaces?

### ISSUE THREAD

**Issue by smitty-exos** [Ubiquiti-App/UNMS#167]
Just installed and started playing with this. Discovery and adding the devices went smooth. However, seems like this isn't up to par just yet. I imagine this is not a firmware issue, but rather a service/functionality issue.

My current set up on a ER-POE5, is as follows. 
3 Gre Tunnels with ipsec....These do not show up in interfaces.
Switch0 has 3 Vlans....These DO show up in the interface listings.
DHCP running on all 3 VLANs. When selecting DHCP Server/Leases it just constantly refreshes and nothing displayed
Routing->OSPF contantly refreshes and nothing displayed

show interfaces 
Codes: S - State, L - Link, u - Up, D - Down, A - Admin Down
Interface    IP Address                        S/L  Description                 
---------    ----------                        ---  -----------                 
eth0         <REMOVED>/24                 u/u  WAN                         
             <REMOVED>/128
eth1         192.168.55.1/24                   u/u  DMZ                         
eth2         -                                 u/u                              
eth3         -                                 u/u                              
eth4         -                                 u/D  AP Uplink                   
lo           127.0.0.1/8                       u/u                              
             192.168.254.1/32                 
             ::1/128                          
nat64        -                                 A/D                              
switch0      192.168.1.1/24                    u/u  MGMT                        
             <REMOVED>/64        
switch0.3    192.168.9.1/24                    u/u  VOIP                        
switch0.10   172.16.0.1/24                     u/u  SMiTTY                      
             <REMOVED>/64        
switch0.42   192.168.42.1/24                   u/u  LAB                         
             <REMOVED>/64        
tun0         192.168.200.1/30                  u/u  Allgood                     
tun1         192.168.200.5/30                  u/u  Smyff                       
tun3         192.168.200.9/30                  u/u  Ashleigh 

show ip ospf route

OSPF process 0:
Codes: C - connected, D - Discard, O - OSPF, IA - OSPF inter area
       N1 - OSPF NSSA external type 1, N2 - OSPF NSSA external type 2
       E1 - OSPF external type 1, E2 - OSPF external type 2

C  172.16.0.0/24 [1] is directly connected, switch0.10, Area 0.0.0.0
O  192.168.10.0/24 [11] via 192.168.200.6, tun1, Area 0.0.0.0
O  192.168.22.0/24 [20] via 192.168.200.2, tun0, Area 0.0.0.0
O  192.168.30.0/24 [20] via 192.168.200.10, tun3, Area 0.0.0.0
O  192.168.44.0/24 [20] via 192.168.200.2, tun0, Area 0.0.0.0
C  192.168.55.0/24 [10] is directly connected, eth1, Area 0.0.0.0
C  192.168.200.0/30 [10] is directly connected, tun0, Area 0.0.0.0
C  192.168.200.4/30 [10] is directly connected, tun1, Area 0.0.0.0
C  192.168.200.8/30 [10] is directly connected, tun3, Area 0.0.0.0

**Comment by smitty-exos** [comment]
Now all of a sudden it is showing. Looks like there was an issue with 2 of the containers constantly restarting. I updated and all seems well at the moment

**Comment by smitty-exos** [comment]
Still not showing tunnel interfaces however.

**Comment by MajoV** [comment]
https://community.ubnt.com/t5/UNMS-Beta/List-tunnel-and-bonding-interfaces/m-p/2225683#M4093

**Comment by smitty-exos** [comment]
Gotcha...On feature request list. Closing.
