### ISSUE TITLE
UNMS maintenance not detecting new 0.14.0 when trying to update

### ISSUE THREAD

**Issue by javiermatos** [Ubiquiti-App/UNMS#169]
My UNMS instance is not detecting the latest stable 0.14.0 version when trying to update. Maybe it is related with the latest-version file in this repository that was not updated to reflect the latest stable version?

**Comment by radekskrivan** [comment]
Hello, @javiermatos. We decided to run the final version of 0.14.0 for a couple of days without the in-app upgrade. It will appear there very soon if no serious issues appear.
