### ISSUE TITLE
[Feature Request ]  Syslog Support

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#17]
Integrate Syslog support as well here so it can be logged to our syslog server as we already use it for other EdgeOS Platforms. though if it will cause the Beta or V1 release from coming out in time then lets plan for a later release for it.

Ideas?

@amishgenius 
@JimBouse
@Alan87i 
@1WisTech1

**Comment by Magician17** [comment]
I would like to see a " Timed Monitor" on syslog... for example lets say a router has been randomly crashing and I need short term logging. For example the crashes some of use\ have had with Infinity.  We can set a time to enable.  I can't say I would want k's of devices sending syslog.

**Comment by ubnt-davids** [comment]
This seems like a good idea, kinda like what i had with the cable plant, we can turn on extra logging for 24hr / 48hr / 72hr or custom define time + return to normal operations after logging event has passed. @jflidr

**Comment by radekskrivan** [comment]
Suggested in https://community.ubnt.com/t5/UNMS-Feature-Requests/Output-to-External-Syslog-Server/idi-p/1815894
