### ISSUE TITLE
UNMS app throws "Unknown Error"

### ISSUE THREAD

**Issue by cYrAx157** [Ubiquiti-App/UNMS#174]
My Server has a UNMS-Setup via Apache Reverse-Proxy.
Login via Webinterface is functioning as expected, but when I try to login to my controller via the UNMS App it fails with an "Unknown Error" (see attached screenshot).

![Screenshot_20190805-163532](https://user-images.githubusercontent.com/11156921/62473027-3e563c00-b7a0-11e9-8d9c-048c4f18ec27.jpg)

**Comment by radekskrivan** [comment]
Hello @cYrAx157, please create a thread about this issue on the [UNMS community forum](https://community.ui.com/tags/unms). Make sure to include the OS of your mobile device, version of UNMS mobile app, version of UNMS controller and if you are using any custom ports there.
