### ISSUE TITLE
Unms Key missing?

### ISSUE THREAD

**Issue by codedmind** [Ubiquiti-App/UNMS#179]
Since upgrade to 1.1.4 the settings connection is missing i cannot find where to get the unms key.

**Comment by Tbsteele** [comment]
Under devices tab add device top right then copy key

**Comment by radekskrivan** [comment]
Hello @codedmind. The comment from @Tbsteele is accurate.
![001](https://user-images.githubusercontent.com/33317055/74223107-47c3e200-4cb6-11ea-9fbe-cd84300e24ec.png)
