### ISSUE TITLE
[Feature Request ] Log Login Attempt Failures

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#18]
Currently i do not see a way where i can see who has attempted to login with a failed password. We should log this to ( Log - Info ) / #17 / email also we should have a white listed ip that is never blocked ie the host unms server ip. Also if with #16 if the max password attempts have been used it will lock the account on the ldap server, and inform them to contact the systems administrator.

Ideas?
@1WisTech1
@amishgenius 
@JimBouse
@Alan87i

**Comment by jflidr** [comment]
We will log failed attempt to login in the version 0.7.12. I will check a possibility of LDAP integration.

**Comment by Dstahl0** [comment]
Integrated into 0.7.12, but the user name is truncated to early to see full username that was typed.


 
![screen shot 2017-02-13 at 9 32 57 pm](https://cloud.githubusercontent.com/assets/14851974/22912551/0861d0e8-f234-11e6-91be-ffbb3c447065.png)

**Comment by jflidr** [comment]
The truncation is intentional. It's a good practice to not log complete username for failure login attempts. There is a common mistake when users write their passwords to username input and these log lines could expose their passwords.

**Comment by radekskrivan** [comment]
Already implemented
