### ISSUE TITLE
[Feature Request ] Log Who Moves Devices / Approves Authorizations 

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#19]
Currently it does not show who has moved or approved what device. We should have the line also list who moved or approved the device. Also it does not log what device port has been disabled ie if i disable a port on a ER-X-SFP via unms it does not log this anywhere, we need this to keep track of what is disabled and by whom as wisp / fisp need to be able to keep track.

Old:
![screen shot 2017-01-29 at 10 28 54 am](https://cloud.githubusercontent.com/assets/14851974/22405250/d34f3e04-e60d-11e6-9a67-4e8e1958046e.png)

New

![screen shot 2017-01-29 at 10 30 08 am](https://cloud.githubusercontent.com/assets/14851974/22405252/f2981556-e60d-11e6-8815-dd328ebb2d04.png)

@JimBouse
@amishgenius
@1WisTech1
@Alan87i

**Comment by jflidr** [comment]
Yes, it is a good idea, we will add it in the version 0.7.13.

**Comment by jflidr** [comment]
It's fixed in the version 0.7.12.
