### ISSUE TITLE
[Feature Request / Nice To Have ] Clickable Device Name in Log Window.

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#20]
Having the "DeviceName" click able would a "Nice To Have" function within the log window as it is one less thing to a person or Tech will need to do to get to the device window.

Does not need to be added asap...
![screen shot 2017-01-31 at 4 00 37 pm](https://cloud.githubusercontent.com/assets/14851974/22493314/73626eb6-e7fd-11e6-9712-03dbe8441380.png)

Ideas?

**Comment by jflidr** [comment]
There is a device icon at the right corner of each log line which opens device detail. I understand that it will be better to have clickable device name.

**Comment by Dstahl0** [comment]
👍

**Comment by jflidr** [comment]
It's fixed in the version 0.7.12.
