### ISSUE TITLE
[Feature Request ] Increase Statistics Logging. 

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#21]
While speaking to @JimBouse, some customers would like to see what they have done over a period of time say 3 months, as of now it only goes to month. is there a way we can Increase the graphing period to more then a month? i only see the custom option being a valid additional option here as users might be asking for 2 months vs if having just 3 months on a tab, this way if we have a custom range, we are catering to all users.

From:
Day | Week | Month 

To
Day | Week | Month | Custom

**Comment by jflidr** [comment]
As a quick solution we are going to add 3 moth and 1 year period to UNMS version 0.7.13. Custom mode is more complex and we will need more time to found appropriate solution for it.

**Comment by Dstahl0** [comment]
Thank you very much, this will do. 👍

**Comment by jflidr** [comment]
UNMS 0.7.13 is out and it includes 3 months and 12 months graphs.
