### ISSUE TITLE
[Bug] [Repost]  routers lose connectivity.

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#22]
Rebelwireless Said: I have a couple devices that are going 'disconnected', if I reboot the device it comes back, if I disable and re-enable UNMS on device it reconnects.

Thread [Here](https://community.ubnt.com/t5/UNMS-Next-Generation-Network/BUG-routers-lose-connectivity/m-p/1829988#U1829988)
---------------------------------
@jflidr  i will keep a look out for this bug that was reported by Rebelwireless.  i have not had this happen yet as i am opening this Trac so i can keep better tracking of the steps to reproduce.

**Comment by Dstahl0** [comment]
I think i just spotted something when setting the new lab up, i will keep a eye out for it. i have not had this happen till now when running everything from a fresh install.

**Comment by jflidr** [comment]
@Dstahl0 We identified a few problems with connectivity. We have a new FW with fixes. We are testing it internally. I suppose that we will release it next week.

**Comment by Dstahl0** [comment]
Thanks for the update @jflidr .

**Comment by jflidr** [comment]
Problems with connectivity are fixed in FW 1.9.6alpha2. It's possible to upgrade to this version via Discovery manager or install it manually. We will publish this FW to community during next week.

**Comment by jflidr** [comment]
FW 1.9.6alpha2 is available.
