### ISSUE TITLE
Cannot download config backup

### ISSUE THREAD

**Issue by mmilata** [Ubiquiti-App/UNMS#23]
Clicking on the *DOWNLOAD* action of a saved configuration backup doesn't seem to do anything. Please let me know if I can provide any other information.

Using UNMS 0.7.12.

**Comment by Dstahl0** [comment]
@mmilata Do you mean the "Download" button for the Backup Data Retention?

![screen shot 2017-02-20 at 5 32 58 pm](https://cloud.githubusercontent.com/assets/14851974/23144000/a5c55202-f792-11e6-8475-fe9b9bbcca71.png)

**Comment by mmilata** [comment]
@Dstahl0 sorry, I meant clicking on *DOWNLOAD* in the *ACTIONS* row in the list of device's configuration backups. Does it work for you?
![unmsbackup](https://cloud.githubusercontent.com/assets/85857/23144537/932fb4f8-f7c8-11e6-9842-c8d139643c1a.png)

**Comment by mmilata** [comment]
Actually I can't download the Backup Data Retention file either so it's not specific to device backups.

It seems to be working fine on Chromium but not with Firefox - tried fresh profile without any addons but still no luck. I'm using Firefox 51.0.1 on x86_64 Fedora 24.

**Comment by Dstahl0** [comment]
Works fine on Chrome Version 56.0.2924.87 (64-bit) macOS Sierra. 10.12

i can confirm with the latest firefox non dev builds' that it does not work on macosx.

Great find @mmilata 

@jflidr

**Comment by jflidr** [comment]
It's fixed in the version 0.7.13.
