### ISSUE TITLE
[Bug] stage-to-prod.sh, version 0.7.13-dev

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#25]
Just to see what it would do when running the command line on the wiki it says...

ERROR: for unms  Cannot start service unms: driver failed programming external connectivity on endpoint unms (e73f351938afa786428f482936a6f21503602828fcc365884bf060b1343ba1d6): Bind for 0.0.0.0:443 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
Failed to start docker containers

**Comment by jflidr** [comment]
You are really quick :-) We changed installation scripts internally. You can use the same command for stable version, but for dev version you have to use:

`curl -fsSL https://raw.githubusercontent.com/Ubiquiti-App/UNMS/master/install.sh > /tmp/unms_install.sh && sudo bash /tmp/unms_install.sh --version 0.7.13-dev`

Can you try it? We know about a few bugs and problematic parts (nothing big). I think that we will have the release candidate for 0.7.13 during Tuesday. If you run UNMS in your network, you can try the new discovery manager and upgrade to alpha2 firmware.

**Comment by Dstahl0** [comment]
:-) Looks like i have this error coming from 0.7.12 to 0.7.13-dev. i will rebuild the vm right now so i can get at least some feedback to you guys today :)


Digest: sha256:e01ad4202e578a43747c30c05399707283e14e2d071e023997587be4037cc400
Status: Downloaded newer image for ubnt/unms:0.7.13-dev
Creating data volumes.
Starting docker containers.
Creating unms-fluentd
Creating unms-redis
Creating unms-postgres
Creating unms

ERROR: for unms  Cannot start service unms: driver failed programming external connectivity on endpoint unms (f1259d81c47203654ff576d98156b78e95c5a73745388332d35bb9ed6c6279c8): Bind for 0.0.0.0:443 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
Failed to start docker containers
root@unms-dev-build-docker:~#

**Comment by Dstahl0** [comment]
@jflidr Performing a Clean install on a fresh clean vm has worked. i tried from 0.7.12-0.7.13-dev and still was given the error above.

**Comment by jflidr** [comment]
It's fixed. You can try:
`curl -fsSL https://raw.githubusercontent.com/Ubiquiti-App/UNMS/master/install-dev.sh > /tmp/unms_install.sh && sudo bash /tmp/unms_install.sh 0.7.13-dev`
Thank you.

**Comment by Dstahl0** [comment]
Running it against 0.7.12 it tells me this first.

Checking available ports
Port 80 is already in use, please choose a different HTTP port for UNMS. [8080]: 

We should have it detect if unms is running, shut down the containers that are for unms then update? ideas?

**Comment by jaroklima** [comment]
The installation script does just that, can you run `docker ps` to see all running containers and the ports they use?

**Comment by jaroklima** [comment]
@Dstahl0 actualy the correct command to diagnose the problem would be `lsof -i :<port>` .. that will tell us what program is using the port

**Comment by Dstahl0** [comment]
Testing now :)

**Comment by Dstahl0** [comment]
@jaroklima  seem to be working now but i will do some other tests here in a few mins, let me remake a new vm on the vsphere server.

**Comment by Dstahl0** [comment]
@jaroklima 
@jflidr 

Deploying a Fresh Ubuntu 16.04 Then a 0.7.12 docker container, setup the unms username password etc no smtp. then i ran -dev code for the version i am using and it works now. odd that it did it before. i will add this to my weekend testing.

**Comment by jflidr** [comment]
I'm about to close this task. We will open it if it happens again.
