### ISSUE TITLE
[Feature Request ] Detect Flapping Interfaces

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#26]
It would be nice to have some sort of setting per site within the unms controller. unms--site--- then on the router config page have a option for Flapping Detection, and we can define the levels ie if 1gb goes to 100Mbps = Sent Alert Email. if 100Mbps to 1000Mbps, Send Email. 

@jflidr 
@amishgenius
@JimBouse

**Comment by amishgenius** [comment]
That would be awesome. I had an interface drop to 100 meg recently, and I had no way of knowing. The interface should have been sending about 300 meg of traffic, and I realized almost 2 days later that something was wrong. I discovered the interface was at 100 meg instead of gigabit. Rebooting the equipment fixed the issue but it would have been nice to get an alert that there was a problem.

**Comment by jflidr** [comment]
@Dstahl0 @amishgenius You mean detection of accidental configuration change or detection of real traffic throughput which is outside of boundaries?

**Comment by Dstahl0** [comment]
Correct @jflidr  i will design by thought process on it via a UX Example  tonight and post a screen shot in my next reply.

**Comment by Dstahl0** [comment]
To give some idea before UX, 

Example for sames case.
Normal port is at 1000Mbps which is connected to a backhaul link.
Port Flops to 100Mbps
Port Flops to 1000Mbps for a hour.
Port Flops to 100Mbps and stays for two weeks....
Sam was tring to see through out his whole network wtf is the issue.
Lastly he check his Tower Router which is the last thing to check and ti was stuck on 100Mbps.
If we have unms alert us via email on any change in Mbps ,10,100,1000 would be great.

Also i will ad in the other part of your question in a new Trac as its different then this. i will update # here when i get it done.

**Comment by JimBouse** [comment]
Agreed.



Sent via the Samsung Galaxy S7 active, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by radekskrivan** [comment]
Transfered to https://community.ubnt.com/t5/UNMS-Feature-Requests/Detect-Flapping-Interfaces/idi-p/2164620
