### ISSUE TITLE
[Feature Request ] Traffic Flow Detection

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#27]
Being able to define a preset amount of traffic that is passing over a interface which in returns triggers a alert to be sent to the logs and a email to be fired off to the respected person.

I Can see this usefull for Backhaul links where if one normally sees 450Mbps of traffic and the meter on unms is set to 400Mbps+ but traffic is running at 145Mbps and this is where we can trigger a email and log alert to be sent.

The Same goes for higher speeds. Say the backhaul support is 740Mbps. Set the Traffic on unms via the site's router to trigger if traffic goes above say 689Mbps over a predefinded ethx port (Defined Time  ( 1/5/10/ min interval ))

ill UX something up over the weekend.

@jflidr 
@amishgenius 
@JimBouse
@1WisTech1
@Alan87i

**Comment by amishgenius** [comment]
That could be very useful indeed

**Comment by JimBouse** [comment]
Upper and lower bounds would be nice.





Sent via the Samsung Galaxy S7 active, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by Alan87i** [comment]
BIG thumbs up here.

**Comment by Dstahl0** [comment]
Sample UX

![screen shot 2017-03-13 at 5 06 25 pm](https://cloud.githubusercontent.com/assets/14851974/23875372/9a64f5c4-080f-11e7-935d-a302a1123e3a.png)

**Comment by jflidr** [comment]
@Dstahl0 So this should be logging event + send email when traffic on interface eth4 is under 400Mb or over 600Mb for 34 seconds?  Why is there interface selector? I think that it could be a part of all interface editors.

**Comment by Dstahl0** [comment]
Yes each interface on a Router ( Tower Router / GPON OLT ) would have this option. This way if we have a Feed eth0 coming into a Edge Router, then feeding GPON on eth6/eth7 and some sectors on eth3 /eth4 we will know right away if the spike is from our sector customers or gpon customers and not the overall port on eth0. Give the options to the end user to choose how they want to monitor it ether at the Tower Router or GPON Device.


@JimBouse 
@amishgenius

**Comment by JimBouse** [comment]
Psuedo logic:
IF { $InterfaceXYZ $DURATION Bandwidth Average } > $Y OR { $InterfaceXYZ $DURATION Bandwidth Average } < $Z THEN “Alert Account 1,2,3,4,5,etc”

Jim Bouse
Owner
Mobile IT Pro - Brazos WiFi
979-985-5912
jim@brazoswifi.com

**Comment by radekskrivan** [comment]
Transferred to https://community.ubnt.com/t5/UNMS-Feature-Requests/Traffic-Flow-Detection/idi-p/2164686
