### ISSUE TITLE
[Feature Request ] Prevent Unauthorized Network Access too GUI.

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#28]
While some propose the difference of using more "ports" for a inform. Lets see if we can not build a white list of ip addresses that are allowed to communicate to the https gui port / wss

if not we need to have a good upgrade path and possible use of 443 without changing something in a config for the ones that have unms mass deployed on tower routers and switches.

Thanks,
David Stahl

**Comment by branob** [comment]
Don't think white list is going to work. Imagine devices all over internet on dynamic IPs.

**Comment by Dstahl0** [comment]
While that is very possible, some wisp owners have there own dedicated public facing ip and a vpn allowed to connect to the network.

**Comment by levicki** [comment]
I am curious, what is the reason not to use a system (or a dedicated) firewall to limit access to HTTPS port? What is the advantage of whitelist in the software itself?

**Comment by radekskrivan** [comment]
Transferred to https://community.ubnt.com/t5/UNMS-Feature-Requests/Prevent-Unauthorized-Network-Access-to-GUI/idi-p/2164690
