### ISSUE TITLE
[Feature Request ] Optional Inform Port / GUI Port XU Change.

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#29]
Allowing the user to define a set of ports for "Inform" and "GUI" port within unms. This way if they do not like the default setup they can change this to what ever port they wish.

**Comment by Dstahl0** [comment]
Kinda like this @jflidr 
![screen shot 2017-03-14 at 10 32 55 pm](https://cloud.githubusercontent.com/assets/14851974/23931023/3692efa4-0906-11e7-97c3-f0852355852b.png)

**Comment by jflidr** [comment]
@Dstahl0 Yes, that's exactly what we would like to do. It will be a new optional port settings.

**Comment by Dstahl0** [comment]
+1 👍 sounds good.

**Comment by 1WisTech1** [comment]
+1 on this.  I was just asking David about this today.  I've got clients outside of my network I'd like to have communicate to my UNMS behind an Edgerouter here at the office.  Specifying the WSS Listen port, and GUI listen port will be important.  Look forward to seeing this in an upcoming build!

**Comment by jflidr** [comment]
It's possible to use custom [inform port](https://github.com/Ubiquiti-App/UNMS/wiki/Installation-&-Update#-changing-the-device-inform-port-optional) from version 0.7.17.
