### ISSUE TITLE
[ Aesthetic 0.7.13 ]  Adoption Text 

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#30]
When adopting a ER8 into the unms portal under devices i see the following.
![screen shot 2017-03-16 at 5 45 53 am](https://cloud.githubusercontent.com/assets/14851974/23990320/0c5bdb9a-0a0c-11e7-9814-0b07b5f3ad84.png)

Hostname "ubnt"
It says Authorizing "ubnt" but if i look to the left i see its been added.

Is there a way we can get some text to appear as it been added? like "Device Has been Adopted" or something to that affect. i only ask this because some people might go" well i was expecting it to tell me something that it has been added ok"

@jflidr

**Comment by jflidr** [comment]
You are right that this text is confusing. We could change it to:

The device ubnt (ER8) has been authorized and added to UNMS. 

What do you think?

**Comment by Dstahl0** [comment]
Sounds Good to me @jflidr .


Thanks,
David

**Comment by jflidr** [comment]
It's fixed in 0.7.14.
