### ISSUE TITLE
[ Discovery Manager 0.7.13 ] Text Field IP Address.

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#31]
So we have "192.168.1.0/24, 71.47.248.0/21, 172.16.1.0/24, 172.19.0.0/16, 172.18.0.0/16" but there is a space within "172.19.0.0/16, 172.18.0.0/16" which is more then "65535 ip addresses"

Can we get the text  cut down a bit within the range that is auto inserted into the field?
"192.168.1.0/24, 10.10.0.1/20"
![screen shot 2017-03-16 at 6 06 03 am](https://cloud.githubusercontent.com/assets/14851974/23991136/ab500e22-0a0e-11e7-86b9-1252ae78b517.png)

As one might just post and say "hey i can not scan wtf?" like this original post was about till i digged a bit deeper into why.

![screen shot 2017-03-16 at 5 53 58 am](https://cloud.githubusercontent.com/assets/14851974/23991151/b7d278b0-0a0e-11e7-83ce-74e26123274f.png)

Trying to think as a normal end user using this and what one might think.

Hope this helps,
Thanks,
David

@jflidr

**Comment by ubnt-michals** [comment]
Good catch! We try to suggest some ip ranges, but we didn't handled the case when the suggested range might be invalid.

We will fix the issue in the next release.

Thank you for reporting.

**Comment by Dstahl0** [comment]
Thanks @ubnt-michals. :) +1

**Comment by jflidr** [comment]
It's fixed in 0.7.14.
