### ISSUE TITLE
[ Aesthetic 0.7.13 ] DHCP Leases Area Text

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#32]
So when a dhcp is disabled it says unblock... i think we should have it day "Enable / Disable" to match with what is in the Edge Router GU.

Example Below.
![screen shot 2017-03-16 at 6 12 23 am](https://cloud.githubusercontent.com/assets/14851974/23991398/953f9b9c-0a0f-11e7-9b85-1767a61ed91f.png)

New Text.

![screen shot 2017-03-16 at 6 12 23 am](https://cloud.githubusercontent.com/assets/14851974/23991406/a1cb2796-0a0f-11e7-9844-b7d5a34b1cc7.png)
![screen shot 2017-03-16 at 6 14 26 am](https://cloud.githubusercontent.com/assets/14851974/23991459/da599188-0a0f-11e7-85d8-4bb234edd375.png)
![screen shot 2017-03-16 at 6 15 07 am](https://cloud.githubusercontent.com/assets/14851974/23991491/ed38fe88-0a0f-11e7-8722-bfb90a1fdc26.png)

and the same goes with the disable text as well under the interfaces it shows block should show disable or enable depending on the state it is in.

![screen shot 2017-03-16 at 6 28 41 am](https://cloud.githubusercontent.com/assets/14851974/23992036/d99dd748-0a11-11e7-8faa-4b61d1b7bd9e.png)

Thanks,
David.

**Comment by jflidr** [comment]
We will unify it in the next version.

**Comment by jflidr** [comment]
It's fixed in 0.7.14.
