### ISSUE TITLE
[Device Overview Image ] 0.7.13 [ Wrong  Product Image Displayed.]

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#33]
So here is the router newly adopted device which is a ER.

![screen shot 2017-03-16 at 6 17 16 am](https://cloud.githubusercontent.com/assets/14851974/23991618/53046f68-0a10-11e7-8863-b0bde78e8c33.png)

and within UNMS it is showing the logo as a edge point device instead of a EdgeRouter Logo.

![screen shot 2017-03-16 at 6 18 25 am](https://cloud.githubusercontent.com/assets/14851974/23991701/9cc87a54-0a10-11e7-8255-048ddee2b28b.png)

**Comment by jflidr** [comment]
Nice catch, we will fix it in the next version.

**Comment by jflidr** [comment]
It's fixed in 0.7.14.
