### ISSUE TITLE
[Feature Request ] Shell Access GUI into UNMS Host.

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#34]
There are many reasons why we need shell access via the web. i will tag some people here and get there option. Console Redirect output was also talked about with @Magician17 and i will make a new trac for it.

***Request is for shell gui access into the host box and not the unms container.
@jflidr 
@Magician17
@amishgenius
@JimBouse
@1WisTech1
@Alan87i
![screen shot 2017-03-17 at 10 22 28 am](https://cloud.githubusercontent.com/assets/14851974/24047391/e6b530f8-0afb-11e7-951d-33e3f4b4b6aa.png)

**Comment by Magician17** [comment]
yes shell access would be nice and time saving in remote management. I would also like to see a console output option.

**Comment by radekskrivan** [comment]
Transferred to https://community.ubnt.com/t5/UNMS-Feature-Requests/Shell-Access-GUI-into-UNMS-Host/idi-p/2164759
