### ISSUE TITLE
[Feature Request ] Console Access

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#35]
Having Remote Console Access to the actual TTYL* Port would be very useful for us ( UNMS Host / ER/ES/EPR/EPS/OLT) as we do not need to be onsite to access the console port. This is not to be confused with the current wording on "Console" which is miss leading and i will open trac for word change.

![screen shot 2017-03-17 at 10 28 00 am](https://cloud.githubusercontent.com/assets/14851974/24049118/68857516-0b01-11e7-8ad8-f2a790ff5620.png)
@jflidr 
@Magician17
@amishgenius
@JimBouse
@1WisTech1

**Comment by radekskrivan** [comment]
Transferred to https://community.ubnt.com/t5/UNMS-Feature-Requests/Console-access/idi-p/2199711
