### ISSUE TITLE
[Feature Request ] 0.7.13+ Word change within "Devices"

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#36]
Having the word console is miss leading as some more experienced unix / linux users might think it is accessing the onsite/device ttyl port.

Old:
![screen shot 2017-03-17 at 10 26 46 am](https://cloud.githubusercontent.com/assets/14851974/24048871/9d673770-0b00-11e7-9967-61ee017e9cb0.png)

Requested Change:
![screen shot 2017-03-17 at 10 58 27 am](https://cloud.githubusercontent.com/assets/14851974/24048894/ad36cc9c-0b00-11e7-8cf2-9f2556add6ef.png)

@jflidr
@Magician17
@amishgenius
@JimBouse

**Comment by jflidr** [comment]
It's fixed in version 0.7.17.
