### ISSUE TITLE
[Feature Request ] Syslog Server

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#37]

**Comment by Dstahl0** [comment]
While many wisp depend greatly on knowing what is all going on with there ubiquiti devices, it is a good feature to have here within.


Possible window showing that the server is running in green text. 
On the left hand side of the new window have a long box within the window and showing the Device / IP where the ip is clickable. then when the user clicks the device it will show to the right of that have with text box showing what is going on in real time.

@jflidr
@Magician17
@amishgenius
@JimBouse

**Comment by Magician17** [comment]
+10

**Comment by radekskrivan** [comment]
Transferred in https://community.ubnt.com/t5/UNMS-Feature-Requests/Syslog-Server/idi-p/2164766
