### ISSUE TITLE
[Bug] Proxmox Host Security Setting. Failure Too Install UNMS 0.7.13

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#38]
Another SU Had this error. i will install proxmox on a bigger vm and test it over the weekend. i am leaning towards a template that was used...

curl -fsSL https://raw.githubusercontent.com/Ubiquiti-App/UNMS/master/install.sh > /tmp/unms_install.sh && sudo bash /tmp/unms_install.sh
is ERROR: failed to register layer: ApplyLayer exit status 1 stdout: stderr: permission denied Failed to pull docker images

Thanks,
David S.

@jflidr

**Comment by 1WisTech1** [comment]
Interesting, I've got UNMS installed on two separate prox mox machines and didn't see this.  Following.

**Comment by Dstahl0** [comment]
Thanks @1WisTech1  i will contact you over the weekend and compare values.

**Comment by jaroklima** [comment]
@Dstahl0 have you made any progress? If the problem persists, please attach your VM settings, I will try to reproduce... I think this will have more to do with the OS than with Proxmox.

**Comment by ubnt-davids** [comment]
@jaroklima i did not have much luck over the weekend. The other user which had this issue will be reporting back here in a few hours.

**Comment by eiacub** [comment]
the error occurs when installing in a lxc container hosted by proxmox

**Comment by Paetur** [comment]
If this is installed as a Container Template it will not work do to the nature of docker.

Docker tries to alter settings that affects the host, if run in CT (Container Template) this is not allowed.

Installing UNMS as a VM image in Proxmox works.

/Paetur

**Comment by radekskrivan** [comment]
Hello. I am closing this thread since it is no longer active. In case you still need our help, please leave a comment.

**Comment by dutch2005** [comment]
you can install unms in a unprivileged container, just enable "keyctl" and "nesting".

Assign the needed ram 2GB recommended and it'll work just fine (i've tested it with ubuntu 18.04.x)

**Comment by dutch2005** [comment]
> If this is installed as a Container Template it will not work due to the nature of docker.
> 
> Docker tries to alter settings that affects the host, if run in CT (Container Template) this is not allowed.
> 
> Installing UNMS as a VM image in Proxmox works.
> 
> /Paetur

Install it as a unprivileged container and it will work ;-)
