### ISSUE TITLE
[Bug]  0.7.13 [ Devices--->Site -- > General ]Settings do not Apply.

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#39]
Running the lastest firmware from the forums A2 for the router and 0.7.13 for unms

When doing the following below and then hitting save, nothing appears to be saved into the router that is being edited.

![screen shot 2017-04-01 at 8 49 43 am](https://cloud.githubusercontent.com/assets/14851974/24578865/3c489de4-16b8-11e7-9e43-0546a7fc0551.png)

After hitting save this is what is reverted.
![screen shot 2017-04-01 at 8 54 48 am](https://cloud.githubusercontent.com/assets/14851974/24578892/eb7dd234-16b8-11e7-8e22-3594ef5238fb.png)

**Comment by jflidr** [comment]
Thank you for reporting it. Could you please try it again (for example rename your device) and then send me your UNMS logs via email? Thank you

**Comment by Dstahl0** [comment]
I'v sent the email to you @jflidr

**Comment by jflidr** [comment]
It's fixed in 0.7.14.
