### ISSUE TITLE
Self Include Google Fonts.

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#4]
We can not depend on the user to have a active internet connection for the font file. Can we self include the font files?

File: /public/index.html
Code `<link href="//fonts.googleapis.com/css?family=Cousine|Lato:100,300,400,700,900" rel="stylesheet" type="text/css">`

**Comment by jflidr** [comment]
Yes, it's a good idea. We will fix it in the next version (0.7.8)

**Comment by jflidr** [comment]
Fixed in version 0.7.8
