### ISSUE TITLE
[Bug] connection speed

### ISSUE THREAD

**Issue by MajoV** [Ubiquiti-App/UNMS#41]
![snimka](https://cloud.githubusercontent.com/assets/26937202/24722343/b71eee40-1a43-11e7-8167-b5f6f460d41d.PNG)

port is disconnected but connection speed is shown, "n/a" will looks better

**Comment by jflidr** [comment]
It's fixed in 0.7.14.

**Comment by MajoV** [comment]
0.7.14 - After clicking ACTION BLOCK on DISCONNECTED port connection speed is back
![snimka](https://cloud.githubusercontent.com/assets/26937202/25308811/6248ba86-27bd-11e7-8f40-08126d2bf003.PNG)

**Comment by jflidr** [comment]
Thank you for reporting it, we will fix it in UNMS 0.7.15.

**Comment by jflidr** [comment]
It's fixed in the version 0.7.15.
