### ISSUE TITLE
[Bug] VLAN interfaces not showing TX/RX data

### ISSUE THREAD

**Issue by arebacollins** [Ubiquiti-App/UNMS#42]
ERPro-8 - 1.9.7alpha1

VLAN interfaces show up green as active in the edgerouter, interfaces summary, but dont show traffic passing through them. Only the physical interfaces show traffic passing through.

**Comment by jflidr** [comment]
Thank you for reporting this bug. We will fix it in the next version. Community link: https://community.ubnt.com/topic/292513/no-statistics-for-vlans

**Comment by jflidr** [comment]
It's fixed in the version 0.7.15.
