### ISSUE TITLE
[Feature Request] Bind docker to a specific IP address

### ISSUE THREAD

**Issue by micko** [Ubiquiti-App/UNMS#43]
I would like to be able to bind the docker image to a specific IP address (interface alias) to be able to run UNMS and UCRM on the same server/virtual machine.

**Comment by jaroklima** [comment]
We will add an optional installation script argument to specify the interface. Target date is TBD.

**Comment by AdmrLechuza** [comment]
+1

**Comment by rdamazio** [comment]
I would add to this the ability to use macvlan networking, by specifying which docker network the containers should join (as well as the IP for each).

**Comment by radekskrivan** [comment]
Moved to [feature request](https://community.ubnt.com/t5/UNMS-Feature-Requests/Bind-docker-to-a-specific-IP-address/idi-p/2199766) thread
