### ISSUE TITLE
[Feature Request] Filter outages / traffic

### ISSUE THREAD

**Issue by arebacollins** [Ubiquiti-App/UNMS#44]
Would be good to have start time/date / end time/date for statistics to drill down or see specifics of outages on statistics in addition to the Hour/Day/Month/Quarter/Year drill downs.

**Comment by radekskrivan** [comment]
Transferred to https://community.ubnt.com/t5/UNMS-Feature-Requests/Filter-outages-traffic/idi-p/2210387
