### ISSUE TITLE
[Bug] ERLite3 DHCP Leases truncated

### ISSUE THREAD

**Issue by Chigerama** [Ubiquiti-App/UNMS#45]
UNMS 0.7.14
ERLite3 1.9.7-a1

As per image below, only the first DHCP lease is showing up per page of leases on the lease page  for the EdgeRouterLite. I'm not sure if this behavior is displayed with other models or only the ERL. 

I can navigate to the second page of leases, however again only the first lease on that page is displayed. 

There are 13 leases total on that DHCP server.

![image](https://cloud.githubusercontent.com/assets/28206280/25559606/fbb3c5cc-2d70-11e7-8550-93dadcbf2eac.png)

![image](https://cloud.githubusercontent.com/assets/28206280/25559640/add8b4ce-2d71-11e7-8467-dc99b0b63fcc.png)

**Comment by jflidr** [comment]
Thank you for reporting this bug. There are more information about it in this community post: https://community.ubnt.com/topic/291344/dhcp-leases-bug

**Comment by jflidr** [comment]
It's fixed in the version 0.7.15.
