### ISSUE TITLE
[Bug] Showing records in LOGS using filtering

### ISSUE THREAD

**Issue by MajoV** [Ubiquiti-App/UNMS#46]
I would like to refer bug regarding LOGS filtering. Please see pictures bellow. Number of showing records does not respond to header.

![log1](https://cloud.githubusercontent.com/assets/26937202/25779052/915c4970-330f-11e7-9755-61f47f2c0b20.PNG)

![log2](https://cloud.githubusercontent.com/assets/26937202/25775378/21f92348-32a4-11e7-9e95-130a9e34a3f1.PNG)

The same I found in Task Manager

![tm1](https://cloud.githubusercontent.com/assets/26937202/25775385/4d4d65fe-32a4-11e7-818e-634c7004555b.PNG)
Using version 0.7.16

**Comment by jflidr** [comment]
@MajoV Thank you for reporting it. It’s a bug and we will fix it. Pagination is not updating properly when you update tasks/logs filter.

**Comment by MajoV** [comment]
@jflidr Can you please check the same problem in OUTAGES? I have no QUALITY data to test it.

**Comment by jflidr** [comment]
@MajoV Yes, we will check it. It's the same component so there is probably the same bug.

**Comment by MajoV** [comment]
@jflidr  I just want to remind you that the same bug is in "Logs" filter by "Devices"

![lfbd](https://cloud.githubusercontent.com/assets/26937202/25968915/6009a4e4-3693-11e7-9d81-a7872e8cfd2e.PNG)

**Comment by jflidr** [comment]
@MajoV Thank you for reporting it. It's fixed as well. Fix will be available in the next release.

**Comment by MajoV** [comment]
@jflidr Thank you

**Comment by jflidr** [comment]
It's fixed in version 0.7.17.
