### ISSUE TITLE
[Task] Installation & Update guide UNMS data wrong location

### ISSUE THREAD

**Issue by tomhumphrey** [Ubiquiti-App/UNMS#47]
In the wiki it shows that the UNMS data is stored at:
`/home/unms/data`
However, I think it should be at
`/home/app/unms/data`

**Comment by jaroklima** [comment]
@tomhumphrey UNMS data is stored in multiple locations inside the Docker container, one of which is `/home/app/unms/data`. All of the data is mapped to `/home/unms/data` on the Docker host.
User `app` in the container has the same UID and privileges as user `unms` on the host.
So the path on the wiki is correct, but I'll change the wording to stress that it refers to the host machine.
