### ISSUE TITLE
[Bug] FIRMWARE MANAGER - firmware upload

### ISSUE THREAD

**Issue by MajoV** [Ubiquiti-App/UNMS#48]
I would like to refer maybe bug regarding FIRMWARE MANAGER
It is possible several times to upload the same firmware.

![fwup1](https://cloud.githubusercontent.com/assets/26937202/25803676/438d725c-33f8-11e7-94aa-f638e58aa415.PNG)

After this step, the number of manual firmware uploads increases, but it does not match the listing.

![fwup2](https://cloud.githubusercontent.com/assets/26937202/25803681/497657ce-33f8-11e7-99d8-d346352fbd43.PNG)

It would be good to solve duplicate uploading of the same firmware.

Using version 0.7.16

**Comment by jflidr** [comment]
@MajoV Thank you for reporting it. We will fix the counter.

**Comment by jflidr** [comment]
It's fixed in version 0.7.17.
