### ISSUE TITLE
[Feature Request] Mail Alert Time

### ISSUE THREAD

**Issue by MajoV** [Ubiquiti-App/UNMS#49]
I have to report what I found. There is time difference in UNMS Mail notification and OUTAGES or LOG time.
In my case 2 hour. See pictures bellow. This is log of one outage.

![tout2](https://cloud.githubusercontent.com/assets/26937202/26037304/d8ff7a0e-38f0-11e7-9a8e-8676ba8ebb6e.PNG)

![tout](https://cloud.githubusercontent.com/assets/26937202/26037307/da92ffc6-38f0-11e7-871a-735ca527da90.PNG)

![tout1](https://cloud.githubusercontent.com/assets/26937202/26037309/db9f3ea2-38f0-11e7-8e29-b24ff3084756.PNG)

ER-X Time zone Europe/Bratislava
VM Time zone Bratislava
UNMS 0.7.16

**Comment by jflidr** [comment]
There will be possible to set UNMS server timezone in the next UNMS version 0.7.17. The correct timezone of your UNMS server will fix this issue.

**Comment by jflidr** [comment]
It's possible to configure UNMS timezone in the last version 0.7.17.
