### ISSUE TITLE
Suspended: reason for suspension

### ISSUE THREAD

**Issue by arebacollins** [Ubiquiti-App/UNMS#50]
The default reason for suspension is payment, and given a drop down where you choose the reasons, is there a configurable setting where suspension reasons can be added? I cant seem to find it.

**Comment by UBNT-Petr** [comment]
yes, the reasons list can be edited in System > Other > Reasons for suspending service

Please, post new questions and requests directly to the UCRM forum, so that it can be shared with all the UBNT community: https://community.ubnt.com/t5/UCRM-Complete-WISP-Management/bd-p/UCRM
