### ISSUE TITLE
[Bug] Firmware counter

### ISSUE THREAD

**Issue by MajoV** [Ubiquiti-App/UNMS#51]
Counter "ALL" make changes when I change type of Firmware.

![fm01](https://cloud.githubusercontent.com/assets/26937202/26522191/0f12fb84-42fb-11e7-9943-579c6039782c.PNG)

![fm02](https://cloud.githubusercontent.com/assets/26937202/26522192/18fac3b6-42fb-11e7-97c2-8f1092f17b15.PNG)

![fm03](https://cloud.githubusercontent.com/assets/26937202/26522193/1acbbc5e-42fb-11e7-9f8b-c83406aedbd7.PNG)

![fm04](https://cloud.githubusercontent.com/assets/26937202/26522195/1c6bcab8-42fb-11e7-8dd8-04c6bf35f666.PNG)

**Comment by ubnt-michals** [comment]
I can confirm the issue, it will be fixed in the next release

**Comment by jflidr** [comment]
It's fixed in UNMS 0.7.18.
