### ISSUE TITLE
[Task] TASK MANAGER - TASK DETAIL

### ISSUE THREAD

**Issue by MajoV** [Ubiquiti-App/UNMS#52]
I think TASK DETAIL will always be only one record. Or this window is now  ready for more features?

![tdfu](https://cloud.githubusercontent.com/assets/26937202/26600016/cbc0ef58-457a-11e7-9e3b-3bacb184e754.PNG)

**Comment by jflidr** [comment]
@MajoV You can start FW mass upgrade already and there will be for example 5 EdgeRouters. Current UNMS version supports only one parallel upgrade so they will run one by one but we will support true parallel upgrades very soon. This screen will show details for a lot of different tasks. For example mass configuration upgrade in near future etc.

**Comment by MajoV** [comment]
@jflidr Thank you for explaining the future features of this screen.
