### ISSUE TITLE
[Bug] [Feature Request] Display IP addresses of DHCP and PPPoE interfaces

### ISSUE THREAD

**Issue by Paetur** [Ubiquiti-App/UNMS#53]
At current version (0.7.18), I have no way of knowing how to get to my routers in UNMS, since there's no 'Report IP' in Devices view, and no PPPoE nor DHCP IP display in 'Devices -> Router -> Interfaces'.

![unms-interfaces](https://user-images.githubusercontent.com/29334235/27003005-b32334b4-4de6-11e7-9d38-3d8330225b45.png)

/Paetur

**Comment by jflidr** [comment]
@Paetur 
Thank you for reporting it. Could you please post image with your interfaces from device UI? 

> 'Report IP' in Devices view
It's hard to say what it should be. It could be **eth0** address, **switch** address, address of interface via **UNMS** is connected etc. So that is why we don't show one address per device in Devices view.

> no PPPoE nor DHCP IP display in 'Devices -> Router -> Interfaces'.
This seems to be a bug. UNMS should show all addresses which are visible in the device UI. Could you please compare it with device UI? Thank you.

**Comment by Paetur** [comment]
> Could you please post image with your interfaces from device UI

![ifandips](https://user-images.githubusercontent.com/29334235/27090347-e3b4eb02-5054-11e7-8f86-1a568b408fd1.png)

> It's hard to say what it should be. It could be eth0 address, switch address, address of interface via UNMS is connected etc. So that is why we don't show one address per device in Devices view.

There are many ways to display this depending on preferance.
1. The interface with the 'default route', would be most likely. 
2. IF the reporting daemon reports which IP it is coming from, and it turns out to be other than def. IF, then rule #1 is not true. 
3. And/or whatever IP is set as 'source IP' on the incoming package TO the server, is the 'reported IP'. 
This could end up being a 'non-clickable' to connect to, if behind NAT, but still valid.

BUT, if you have DHCP and PPPoE IP's shown, I can live without a 'report IP'.

/Paetur

**Comment by jflidr** [comment]
Missing address for **eth4.200** is a bug and we will fix it in the next version. Support for PPPoE port which is created for VLAN port is missing in the current UNMS version. We will add it but it will not be in the next version because it's more complex.

**Comment by jflidr** [comment]
VLAN problem is fixed in 0.8.0.

**Comment by radekskrivan** [comment]
This had been fixed in 0.10.0+
