### ISSUE TITLE
[Bug] Interface sort order

### ISSUE THREAD

**Issue by Paetur** [Ubiquiti-App/UNMS#54]
In the webUI the sort order by interface is near perfect (apart from the pppoe, which is downstream from eth4.110).

![1](https://user-images.githubusercontent.com/29334235/27095623-51654bc2-5066-11e7-92c9-af876d844bd3.png)

Where as the UNMS sort looks to be by alphabet ordre based on description.

![2](https://user-images.githubusercontent.com/29334235/27095768-c6821002-5066-11e7-837c-4786f5e32643.png)

/Paetur

**Comment by MajoV** [comment]
@Paetur 

It is ready now.
This is Table columns editor in version 0.7.18 and you can enable ID

![nf](https://user-images.githubusercontent.com/26937202/27101603-b7bf5950-5082-11e7-9a05-937d9162025b.PNG)

and your screen will look like this, sorted by ID

![name](https://user-images.githubusercontent.com/26937202/27101685-0b903c52-5083-11e7-833e-7be2b4674b0c.PNG)

**Comment by MajoV** [comment]
@jflidr 

Look at my edited screen.
Omitting interfaces in brackets can look better.

![namech](https://user-images.githubusercontent.com/26937202/27104620-2b04178e-508d-11e7-8f0a-62f752790026.png)


Suggestions?

**Comment by Paetur** [comment]
@MajoV Thanks for pointing that out.

I agree omitting (<IF>) in the Name/Description field, now that the ID field is present.

/Paetur

**Comment by MajoV** [comment]
@Paetur thank you, but in this case needs to be ID in columns editor enabled by default

**Comment by jflidr** [comment]
UNMS version 0.8.0 includes three attributes:
- **id:** eth0
- **description:** Management
- **name:** Management (eth0)
