### ISSUE TITLE
Doesn't deploy inside LXC

### ISSUE THREAD

**Issue by bbabich** [Ubiquiti-App/UNMS#57]
Perhaps by design, however your installer doesn't complete when running inside an LXC. 

> Step 4/6 : RUN apk add --no-cache --update su-exec     && apk add --no-cache dumb-init --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/     && chmod +x /entrypoint.sh
>  ---> Running in eaa78c5c7262
> ERROR: Service 'fluentd' failed to build: Could not check if docker-default AppArmor profile was loaded: open /sys/kernel/security/apparmor/profiles: permission denied
> Failed to start docker containers

**Comment by WeredPerson** [comment]
It most likely failed because docker uses LXC, You will need to configure your container with the proper hooks to make that work, More info here https://github.com/moby/moby/issues/6783

**Comment by javiermatos** [comment]
Creating the LXC/LXD container with `lxc launch ubuntu-daily:16.04 docker -c security.nesting=true` has shown in https://stgraber.org/2016/04/13/lxd-2-0-docker-in-lxd-712/ did the trick for me.

The installation works fine and it tells "UNMS is running", but there is nothing listening on port 80 or 443 to process the request.

**Comment by aaronstuder** [comment]
Worked for me using the instructions @javiermatos provided.

**Comment by javiermatos** [comment]
I had problems updating UNMS to a version newer than 0.9.4 because of the docker package included in Ubuntu repository. The docker package you install using Ubuntu packages is a bit outdated, so I have uninstalled that package and installed the newest Docker from the official Docker repository https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/ and now it works with the latest version of UNMS which is 0.10.3 right now.

**Comment by juanquy** [comment]
What version of LXD do you have?
make sure you launch your container with :
$ lxc launch ubuntu:16.04 "container-name" -c security.nesting=true

Them edit the container with this :
$ lxc config edit "CONTAINER NAME" and add this line under config:
linux.kernel_modules: ip_tables

restart the container and install UNMS you don't need to install docker from Ubuntu just run the command to install UNMS and I will go to the end where you will see
UNMS not running and I'm at this point trying to figure out what is the issue

**Comment by radekskrivan** [comment]
We are preparing a new installation which will come with prebuild containers and it will not reply on the alpine repository. It should be available in 0.12.0
