### ISSUE TITLE
Failure to install using Ubuntu script

### ISSUE THREAD

**Issue by elf55** [Ubiquiti-App/UNMS#59]
Hi,
following the install instructions for Ubuntu 16.04 LTS (running 16.04.2), the install sequence ends with:

> 
Ign:30 http://ppa.launchpad.net/ubuntu-x-swat/x-updates/ubuntu xenial/main DEP-11 64x64 Icons 
Fetched 2,481 kB in 8s (307 kB/s)                                                             
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/michael-gruz/canon-trunk/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://ppa.launchpad.net/ubuntu-x-swat/x-updates/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/michael-gruz/canon-trunk/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/ubuntu-x-swat/x-updates/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
>

I haven't seen this before, so I'm guessing it's either a problem with the posted distro or I have a security setting that I need to relax.  Any quick fix?  Can I get a procedure to just download the container and install Docker separately?

**Comment by jaroklima** [comment]
You can install Docker and Docker-Compose manually before running the UNMS install script. It will detect that Docker is already installed and skip that step.

**Comment by elf55** [comment]
Indeed.  Pre-installing Docker appears to work.  Thanks.
