### ISSUE TITLE
Easier deployment on Docker orchestrators

### ISSUE THREAD

**Issue by nmaggioni** [Ubiquiti-App/UNMS#61]
Having a more accessible `docker-compose` file would greatly help in deploying UNMS in pre-existing container orchestration systems (Rancher, Docker Swarm...), opposed to having to download the tarball and manually hacking the install script & compose file to not disrupt any existing infrastracture.

A better yet approach could be implementing something like [Rancher's Catalog](http://rancher.com/docs/rancher/v1.6/en/catalog/) deploy templates.

This could also relieve some stress from the installation script, letting the orchestration system handle things like subnets, ports, mounts, SSL termination, etc.

**Comment by nmaggioni** [comment]
I must have missed this: https://github.com/Ubiquiti-App/UNMS/wiki/Manual-installation-using-Docker-Compose

**Comment by jaroklima** [comment]
@nmaggioni that guide is for an older version and it takes a lot of effort to keep it up to date - I don't think it's sustainable long term. We will either have to stick to the installation script or come up with an alternative that won't be much more complicated for the users - one idea is to distribute UNMS as a virtual machine image. Being able to support more than one installation model (install script, orchestrators, virtual machine, APT package) would be nice, but we don't have the resources.

**Comment by radekskrivan** [comment]
Transferred to https://community.ubnt.com/t5/UNMS-Feature-Requests/Easier-deployment-on-Docker-orchestrators/idi-p/2210407
