### ISSUE TITLE
Devices cannot register to UNMS behind reverse proxy

### ISSUE THREAD

**Issue by AlexLardschneider** [Ubiquiti-App/UNMS#62]
Hello,

I installed UNMS on my Amazon EC2 virtual machine and I use Apache as a reverse proxy. 
I used the following command to install UNMS:

```
sudo bash /tmp/unms_install.sh --behind-reverse-proxy --public-https-port 443 --http-port 9080 --https-port 9443
```

The reverse proxy works fine, which means that I can log into the control panel and all functions work as expected, but I cannot register my ER-X when using a reverse proxy. 

In `/var/log/unms.error` I see this error message every time my ER-X tries to contact UNMS:

`ERROR connection error (unms.xxxxxx.com:443): HS: ACCEPT missing`

I found a thread on the [Ubiquiti community](https://community.ubnt.com/t5/UNMS-Ubiquiti-Network-Management/Devices-cannot-register-to-UNMS-behind-reverse-proxy/m-p/2013433#M358) which seems to suggest unsetting the Referer, but unfortunately that does not seem to work in my case.

Are there other configurations needed for UNMS to work behind a reverse proxy?
Registering the ER-X worked fine before I added the reverse proxy.

Best regards,
Alex

**Comment by jflidr** [comment]
Devices use WSS - [WebSocket Secure connection](https://en.wikipedia.org/wiki/WebSocket) for communication with UNMS. Therefore you have to configure your proxy to handle websocket communication with TLS properly on its public-https-port - 443.

**Comment by AlexLardschneider** [comment]
@jflidr thanks for letting me know. Any example on how you would do that using Apache or Nginx?

**Comment by AlexLardschneider** [comment]
Looking at your Nginx reverse proxy example I can see all HTTP/HTTPS requests getting proxied, but I cannot find anything specific to web sockets. The only lines which seem to forward traffic are

```
proxy_pass     https://$upstream;
proxy_redirect https://$upstream https://$server_name;
```

but no mention of web sockets. How come the same configuration in Apache form doesn't work then?

**Comment by jaroklima** [comment]
@AlexLardschneider I haven't had a chance to try Apache yet, but regarding your last question, the bits of the Nginx config that are important for WebSocket are 
```
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}

proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $connection_upgrade;
```

**Comment by AlexLardschneider** [comment]
@jaroklima thanks for getting back to me. I tried switching to Nginx using your config temporarily, which kinda works fine for the Web UI, but I am getting a different error on my ER-X now:

```
2017-08-15 11:05:36 INFO  connecting to unms.xxxxxx.com:443
2017-08-15 11:05:37 INFO  connection established
2017-08-15 11:05:37 INFO  peer closed connection (status 1000): Connection terminated by UNMS while establishing connection.
2017-08-15 11:05:37 INFO  connection closed
```

Do you know what's up with that?

**Comment by radekskrivan** [comment]
Closing this older issue. UNMS is now several versions older. If the issue persists please contact us on our [community page](https://community.ubnt.com/t5/UNMS-Beta/bd-p/UNMSBeta).
