### ISSUE TITLE
nc: bad address 'unms-postgres'

### ISSUE THREAD

**Issue by githubprojects1** [Ubiquiti-App/UNMS#63]
This has already been discussed here
[https://community.ubnt.com/t5/UNMS-Ubiquiti-Network-Management/UNMS-Docker-quot-bad-address-unms-postgres/td-p/2016483](url)

_docker-compose.yml.template_ - line 53 gives image: postgres:9.6.**1**-alpine
but this is no longer available at https://hub.docker.com/_/postgres/

I am new to all this and still trying to figure it out. Not sure if this is even the cause

**Comment by woopstar** [comment]
I believe this is fixed
