### ISSUE TITLE
Random Vertical Line On Graphs

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#7]
Looks like we have a ( The Darker Line to the right ) random vertical line on all the graph's, not sure what is causing this.
OLT Software Version: 0.2.5

![screen shot 2017-01-03 at 12 06 36 am](https://cloud.githubusercontent.com/assets/14851974/21600337/99b78fa4-d148-11e6-8470-365e41fd04d7.png)

Not much telling if anything lost connection or what not.

![screen shot 2017-01-03 at 12 09 19 am](https://cloud.githubusercontent.com/assets/14851974/21600360/f9077a64-d148-11e6-9827-4b84c211b24e.png)

**Comment by jflidr** [comment]
The line is not a random one. It is a day separator in hour/day graph + week separator in month graph. I see that it is confusing. We will remove it.

**Comment by jflidr** [comment]
Fixed in version 0.7.8
