### ISSUE TITLE
[Feature Request] IP Address support for AirMax devices

### ISSUE THREAD

**Issue by neo290** [Ubiquiti-App/UNMS#70]
No IP Address on managment vlan
http://imgur.com/a/ZGEDh

**Comment by Cheprer** [comment]
IP address recognition is for now supported only for EdgeRouters and OLTs. We've found some issues and possible extensions there and implementing them now. Once solved we are planning to develop this feature for AirMax devices as well. I'll rename this issue to IP Address support for AirMax devices and update it once resolved.

**Comment by jflidr** [comment]
Fixed in UNMS 0.11.0
