### ISSUE TITLE
[Feature request] Network topology view

### ISSUE THREAD

**Issue by rdamazio** [Ubiquiti-App/UNMS#72]
It would be really nice if UNMS gave me a topology view of the network, where I can graphically see what routers and switches are connected to what others, which connections are active (e.g. when STP is used), stats about each connection, LLDP information, etc.
This will of course be most important when EdgeSwitch is also supported, and there's a hundred different ways to build/discover that topology (especially in non-pure-Ubiquiti environments). It's also possible to show different types of topologies - e.g. the pure physical topology, the L2 topology, L3 topology (with OSPF/BGP info), etc. Of course, I'd love to have all of them available :)

Worst case, if you all can't prioritize building the automatic topology discovery, being able to manually specify the physical topology and just see its drawing and stats about the links would still be nice.

**Comment by radekskrivan** [comment]
Transferred to https://community.ubnt.com/t5/UNMS-Feature-Requests/Network-topology-view/idi-p/2210403
