### ISSUE TITLE
UNMS restarting every minute or so with error

### ISSUE THREAD

**Issue by briellie** [Ubiquiti-App/UNMS#79]
Hello, UNMS 0.10.0 appears to be crashing and restarting every minute or so.  When I attach to the docker container for unms, the following is the error:
[unms-error1.txt](https://github.com/Ubiquiti-App/UNMS/files/1327820/unms-error1.txt)

Any workaround I can do quickly to get it back up and running?

**Comment by jflidr** [comment]
Hi @briellie, it's crashing, because there is a problem with parsing data from one EdgeRouter. You can for example disable UNMS connection on it. We will fix it ASAP in 0.10.1.

**Comment by briellie** [comment]
Much appreciated looking into the error!   I rolled back to 0.9.4 from backup for now, since I couldn't figure out which one was causing it to disable the connector.

**Comment by jflidr** [comment]
It should be fixed in UNMS 0.10.1
