### ISSUE TITLE
Latency & Outage Yes / No ?

### ISSUE THREAD

**Issue by Dstahl0** [Ubiquiti-App/UNMS#8]
So this isn't very clear / Documented as to what Yes & No means to the right of the image below.
If it means there is a outage, We should have a small (?) bubble icon with a float text box window that states what this means.

OLT Software Version:         0.2.5
UNMS UI Software Version: 0.7.6

![screen shot 2017-01-03 at 12 47 31 am](https://cloud.githubusercontent.com/assets/14851974/21600684/509f3096-d14e-11e6-9a73-674db17862a3.png)

**Comment by jflidr** [comment]
Yes, it means that there is an outage. We will add help (?).

**Comment by Dstahl0** [comment]
Thanks @jflidr
