### ISSUE TITLE
Native VLAN field is empty in ONU Profiles

### ISSUE THREAD

**Issue by hornos** [Ubiquiti-App/UNMS#80]
After updating to 0.10 editing and saving native VLAN field in UNMS shows no problem, but clicking on the Edit again and the Native VLAN filed is empty. I cannot save the native VLAN on the OLT as well and I get the following message: "VLAN ID must not be amongst included VLANs". Although the native VLAN is included in the list.

**Comment by michaelkuk** [comment]
Hello @hornos, thank you for reporting this!

I have investigated the issue and indeed we had bug in our code.

It will be corrected in 0.10.3 release, which is scheduled to be released published this week.

**Comment by jflidr** [comment]
The issue has been fixed in UNMS 0.10.3.
