### ISSUE TITLE
wrong password

### ISSUE THREAD

**Issue by ermeswifi** [Ubiquiti-App/UNMS#84]
hi, i have installed unms yesterday, but today the pass in wrong.....i have tried to reset it, but the reset mail do not arrived. another way to get the pass? or how can i reinstall unms?
giancarlo

**Comment by jflidr** [comment]
Hi @ermeswifi, you can use this tutorial: [Password Recovery](https://github.com/Ubiquiti-App/UNMS/wiki/Password-Recovery).

**Comment by radekskrivan** [comment]
Closing this older issue. If the problem persists please let us know.

**Comment by hamwong** [comment]
HI, how am I able to recovery password for old unms? I am still using unms 0.13 but no instruction previous version

**Comment by radekskrivan** [comment]
Greetings. In order to get support for UISP, please [use the support request form](https://help.ui.com/hc/en-us/requests/new?ticket_form_id=360000076634#UNMS-Hosted) to create a Zendesk ticket, where we will have a look at your issue.
