### ISSUE TITLE
possible patch for systems with nmap-ncat installed

### ISSUE THREAD

**Issue by mathse** [Ubiquiti-App/UNMS#85]
on systems with nmap-ncat installed this error will be shown on installation/upgrade

nc: invalid option -- 'z'
Ncat: Try `--help' or man(1) ncat for more information, usage options and help. QUITTING.

this patch, applied to install-full.sh might fix this (when '-z' is removed on while loops)

function nc { 
if [ -x /usr/bin/ncat ]
  then
    echo | /usr/bin/ncat --send-only $1 $2 2>/dev/null
  else
    /bin/nc -z $1 $2
  fi  
}
export -f nc

**Comment by jaroklima** [comment]
@mathse when I install nmap (`apt-get install nmap` on Ubuntu), it creates `/usr/bin/ncat`, but doesn't remap the `nc` command. All examples also use the `ncat` command, not `nc`. This probably means that it's meant to co-exist with traditional netcat, not replace it. 
It looks like mapping `nc` to `ncat` is the problem and I don't think we should add custom logic to support it.

**Comment by mathse** [comment]
but it would support centos ;-)

**Comment by jaroklima** [comment]
If you are saying that `nc` mapped to `ncat` is the default on CentOS, then we will deal with it when we add CentOS support, which is in our pipeline, but doesn't have high priority at this time.

**Comment by mathse** [comment]
ahhh, great :) 👍 +1

**Comment by woopstar** [comment]
Should be fixed by #103 . Pull request removes netcat in favor of curl

**Comment by jflidr** [comment]
Fixed in 0.11.1.
