### ISSUE TITLE
Impossible to add Devices with PPPoE interfaces

### ISSUE THREAD

**Issue by DiegoMax** [Ubiquiti-App/UNMS#87]
Hello, im having issues adding devices with PPPoE interfaces.

My PPPoE traffic is on a VLAN, so the wan interface for my devices is tagged with VLAN id 10.
Since i seem to be the only one with this issue im posting some details about my network config.

As you can see below, airOS reports that it is succesfully connected to UNMS, however, the device never shows in UNMS.

![screenshot 2017-10-06 21 29 59](https://user-images.githubusercontent.com/97486/31303059-cee971fa-aadd-11e7-8a2e-36df3c072efe.jpg)

This is my WAN config on the CPE:
![screenshot 2017-10-06 21 32 49](https://user-images.githubusercontent.com/97486/31303097-22d1ab66-aade-11e7-8994-568edc8341a8.jpg)

This is the Management and LAN side of the CPE (management vlan is 100)
![screenshot 2017-10-06 21 33 18](https://user-images.githubusercontent.com/97486/31303099-2a8ade40-aade-11e7-8f61-d36244164faf.jpg)

Traceroute from CPE to UNMS ip:
`XW.v6.1.1# traceroute 10.0.120.100
traceroute to 10.0.120.100 (10.0.120.100), 30 hops max, 38 byte packets
 1  10.0.150.1 (10.0.150.1)  16.522 ms  25.044 ms  19.375 ms
 2  10.0.120.100 (10.0.120.100)  35.075 ms  21.014 ms  17.847 ms`

Traceroute from UNMS to CPE:
`$ traceroute 10.10.8.13
traceroute to 10.10.8.13 (10.10.8.13), 30 hops max, 60 byte packets
 1  10.10.8.13 (10.10.8.13)  41.183 ms  42.663 ms  42.673 ms`

Devices in BRIDGE mode, on the exact same network, can be added just fine.
Could you guys point into the right direction ?
Thanks!

**Comment by blackbeeman** [comment]
Same problem, but our bridge mode devices different ip subnet to pppoe devices

**Comment by JoNICK297** [comment]
The same problem. All devices that are behind a router is added to UNMS. Devices PPPoE can't connect to UNMS.

**Comment by JoNICK297** [comment]
Devices connected, but not visible in UNMS

**Comment by radekskrivan** [comment]
@JoNICK297  what version of UNMS are you currently running please?

**Comment by blackbeeman** [comment]
0.10.4 but same with previous. Curiously i have got one only on a different subnet to 'be seen'

**Comment by radekskrivan** [comment]
The reason why I am asking is, that this should be fixed in 0.11.0. There is currently a release candidate of 0.11.0 available and the final version is going to be released soon.

**Comment by blackbeeman** [comment]
Cheers - I gave up trying when I saw the airOS reporting as connected to UNMS - well out of my depth!. I  haven't yet figured the port forwarding necessary for remote sites server by other Mikrotiks!

**Comment by JoNICK297** [comment]
Yes. In version 0.11.0-rc1 all works fine.
