### ISSUE TITLE
Synology install method

### ISSUE THREAD

**Issue by deimosfr** [Ubiquiti-App/UNMS#90]
Hi,

It would be great to provide a way to install it on a synology through Docker.

Thanks

**Comment by julobaco** [comment]
I have running UNMS 0.10.4 on my Synology DS 916+ as virtual machine on Ubuntu 16.04 (app in Synology has name Virtual Machine Manager) and it is working without any problems from beginning :)

**Comment by deimosfr** [comment]
Thanks for the reply @julobaco , but I was asking for Docker. I don't want to add a such overhead just for UNMS which already has many dependencies.

By the way it looks like Virtual Machine Manager is not available for smaller synology like DS713+. So Docker is definitively better.

**Comment by radekskrivan** [comment]
Transferred to https://community.ubnt.com/t5/UNMS-Feature-Requests/Synology-install-method/idi-p/2210406
