### ISSUE TITLE
devices show disconnect

### ISSUE THREAD

**Issue by issamfayad** [Ubiquiti-App/UNMS#93]
I use UNMS to manage 200+ devices. after I upgraded from 0.10.3 to 0.10.4, many devices appeared as disconnected. I tried to refresh key from UNMS UI , but it did not help. The only way that works is by login to device and disable/enable UNMS management service and update key . But this is painful to do that on 60+ devices every time I upgrade. 

I use firmware versions 8.4.3 and 6.1.3

**Comment by radekskrivan** [comment]
@issamfayad  I am sorry to hear that you are having troubles to upgrade UNMS. One thing that can be done to alleviate this problem is to switch Settings -> UNMS -> Device Update Frequency to 'Low' value.
We will look into this issue and try to find out its cause.

**Comment by radekskrivan** [comment]
Hello. I am closing this thread since it is no longer active. In case you still need our help, please leave a comment.
