### ISSUE TITLE
100% CPU in node

### ISSUE THREAD

**Issue by javiermatos** [Ubiquiti-App/UNMS#94]
I have UNMS version 0.10.4 running with Docker version 17.09.0-ce. After adding 100 devices assigned to many sites (4 different sites), the application started to slow down. In htop I see that the container where UNMS is installed (I use UNMS inside Docker inside LXC) is getting 100% CPU usage.

`node --optimize_for_size --max_old_space_size=1000 --max-executable-size=1000 --gc_interval=120 index.js`

What could be the problem? Where can I see logs for errors? Did someone have the same issue?

**Comment by jflidr** [comment]
@javiermatos Hi Javier, could you please try UNMS 0.11.0 and if necessary change your _SETTINGS -> Device -> Device Update Frequency_ to _low_ or _minimal_?

**Comment by javiermatos** [comment]
Hello. Thank you. I upgraded yesterday from 0.10.0 to 0.11.0 and now it
works fine. Thank you. I was always using update frequency in low or
minimal.
