### ISSUE TITLE
0.11.0 beta 1 ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by TamerAljabali** [Ubiquiti-App/UNMS#95]
after clean install on Ubuntu 16.04.2 LTS
we faced a problem in https page 
"ERR_TOO_MANY_REDIRECTS"

**Comment by radekskrivan** [comment]
Hello @TamerAljabali . This may be a browser related issue. Please have a look on [this article](https://www.drivereasy.com/knowledge/how-to-fix-err-too-many-redirects-error/) and please let me know if it doesn't help.

**Comment by radekskrivan** [comment]
Hello. I am closing this thread since it is no longer active. In case you still need our help, please leave a comment.
