### ISSUE TITLE
Section for PtP links or backbone

### ISSUE THREAD

**Issue by djlucifer** [Ubiquiti-App/UNMS#96]
Hi,
the user interface includes a section of Sites, Endpoints and Devices, it could be added a section for PtP links, or section for Backbone

**Comment by radekskrivan** [comment]
Hello @djlucifer,
thank you for an interesting feature request. I would like to encourage you to share it on our community's thread [Feture request](https://community.ubnt.com/t5/UNMS-Feature-Requests/idb-p/UNMSFeatureRequests) where others may support it by voting. It may increase the likelihood of this feature to be implemented.

**Comment by solanetisp** [comment]
I agree!
It would be nice to drag and drop a topology to put clients under their own sector and sectors under backhual.... etc.
