### ISSUE TITLE
debian8: Service 'fluentd' failed to build: cgroups: memory cgroup not supported on this system

### ISSUE THREAD

**Issue by frinnst** [Ubiquiti-App/UNMS#98]
Debian 8 is listed as supported but it appears there are some issues:

Building fluentd
Step 1/6 : FROM fluent/fluentd:v0.12-latest
 ---> ef9be3a6ded0
Step 2/6 : USER root
 ---> Using cache
 ---> 8a40ac23074a
Step 3/6 : COPY entrypoint.sh /
 ---> Using cache
 ---> a4949381f4d7
Step 4/6 : RUN apk add --no-cache --update su-exec     && apk add --no-cache dumb-init --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/     && chmod +x /entrypoint.sh
 ---> Running in 93d602eea1d5
ERROR: Service 'fluentd' failed to build: cgroups: memory cgroup not supported on this system: unknown
Failed to start docker containers

**Comment by radekskrivan** [comment]
@frinnst Hello Fredrik.
It may help you to downgrade your docker or try Debian 9. Here is a [thread ](https://community.ubnt.com/t5/UNMS-Ubiquiti-Network-Management/UNMS-install-on-Debian-failed-Service-fluentd-failed-to-build/m-p/2148112#M2431)where another community member reported the same error.

**Comment by radekskrivan** [comment]
Hello. I am closing this thread since it is no longer active. In case you still need our help, please leave a comment.
