### ISSUE TITLE
Getting devices to connect via UNMS

### ISSUE THREAD

**Issue by cbarratt** [Ubiquiti-App/UNMS#99]
I could be potentially missing something incredibly obvious here so apologies if I'm asking something silly. But I setup my UNMS locally on my network at home, using an externally facing DNS hostname for the setup for the purposes of SSL/LetsEncrypt cert.

This means though, that when I try to get devices to connect via discovery manager, it gives out the UNMS key with the externally facing DNS name - this means that none of my devices can be automatically adopted. I have to manually go to the device, and replace my DNS name with the local IP address - then the device will appear as adopted.

**Comment by radekskrivan** [comment]
@cbarratt Hello Callum. Please have a look at [this article](https://github.com/Ubiquiti-App/UNMS/wiki/Discovery-Troubleshooting), there are some pieces of info about discovery. Also it is quite important which version of UNMS you are running. We had added an internal nginx reverse proxy in version 0.11.0 which will manage the LetsEncrypt certificate by itself.

**Comment by cbarratt** [comment]
Aha! excellent. I'll take a read.

Is there any public way of installing 0.11? I'm currently on 0.10.4 at the minute :)

**Comment by radekskrivan** [comment]
Yes there is release candidate of 0.11.0 available.
You can update your UNMS with this command:

> curl -fsSL https://raw.githubusercontent.com/Ubiquiti-App/UNMS/master/install.sh > /tmp/unms_install.sh && sudo bash /tmp/unms_install.sh --version 0.11.0-rc1 --update

Be careful though. Once you upgrade to 0.11.0 rc1 there is no way back to 0.10.4 without complete reinstall which means loosing your data. 
Also after consulting this with our developers I found out that installing 0.11.0 probably won't help you. 
I assumed you are trying to connect devices from outside of the local network where UNMS runs. Our devs explained to me that it is much more likely that you are connecting devices inside your local network and it puts the UNMS reverse proxy completely out of the picture.

We believe you need to setup a local DNS record on your gateway similar to the external facing DNS record. That will point your local devices the same way the external facing DNS is pointing the LetsEncrypt. 
If you are, by any chance, using our EdgeRouter as a gateway to internet .. here is a [guide](https://help.ubnt.com/hc/en-us/articles/115010913367-EdgeRouter-DNS-Forwarding-Explanation-Setup-Options) how to setup the local DNS.

**Comment by cbarratt** [comment]
That's great, I was interested in giving 0.11.0 a test regardless of my problems, so thanks for providing that.

You've essentially nailed the problem there, using an external DNS record for UNMS but discovering local LAN devices, which try to go out to that record which will resolve to the WAN IP (though I'd imagined NAT Hairpin potentially could take care of it but, maybe not).

I do have an ERX indeed! I'm going to follow the guide you've provided, that's precisely what I was looking for, how to setup a custom rule 👍

**Comment by cbarratt** [comment]
The DNS forwarding setup worked a treat - I now got back my AirCube with ease! (the only device I couldn't easily manually specify the UNMS WSS URL)
